import { Card } from '../types/game';
import { EncounterDefinition, EchoDungeonDefinition, SubjectInfo } from '../types/curriculum';

export const CS_STARTER_CARDS: Card[] = [
  {
    id: 'cs_initialize',
    name: 'Initialize',
    cost: 1,
    subject: 'computerScience',
    rarity: 'common',
    operationKey: 'INITIALIZE',
    description: 'Instantiate pointers, base case conditions, and loop invariants.',
    effectText: 'Sets left=0, right=n-1. Deals 25 DMG & gains 15 Shield.',
    damage: 25,
    shield: 15,
    iconName: 'Play',
    flavorQuote: 'Every great algorithm begins at state zero.',
  },
  {
    id: 'cs_compare',
    name: 'Compare',
    cost: 1,
    subject: 'computerScience',
    rarity: 'common',
    operationKey: 'COMPARE',
    description: 'Inspect elements at pointer indices to test ordering predicate.',
    effectText: 'Evaluates array[i] > array[j]. Deals 20 DMG & draws 1 card.',
    damage: 20,
    shield: 5,
    drawCards: 1,
    iconName: 'GitCompare',
    flavorQuote: 'Decisions are the bedrock of computation.',
  },
  {
    id: 'cs_swap',
    name: 'Swap',
    cost: 1,
    subject: 'computerScience',
    rarity: 'common',
    operationKey: 'SWAP',
    description: 'Exchange misplaced elements to restore sorted invariant.',
    effectText: 'Swaps inverted elements. Deals 35 DMG.',
    damage: 35,
    shield: 10,
    iconName: 'ArrowLeftRight',
    flavorQuote: 'One permutation closer to entropy minimization.',
  },
  {
    id: 'cs_recurse',
    name: 'Recurse',
    cost: 2,
    subject: 'computerScience',
    rarity: 'rare',
    operationKey: 'RECURSE',
    description: 'Decompose the problem into smaller identical subproblems.',
    effectText: 'Calls T(n/2). (Requires base-case validation!). Deals 45 DMG.',
    damage: 45,
    shield: 10,
    iconName: 'Repeat',
    flavorQuote: 'To understand recursion, one must first understand recursion.',
  },
  {
    id: 'cs_memoize',
    name: 'Memoize',
    cost: 1,
    subject: 'computerScience',
    rarity: 'rare',
    operationKey: 'MEMOIZE',
    description: 'Store precomputed subproblem solutions in cache to achieve O(1) lookup.',
    effectText: 'Caches subproblem. Grants 25 Shield & restores 1 Energy.',
    damage: 15,
    shield: 25,
    iconName: 'Database',
    flavorQuote: 'Never calculate twice what memory can hold once.',
  },
  {
    id: 'cs_terminate',
    name: 'Terminate',
    cost: 1,
    subject: 'computerScience',
    rarity: 'common',
    operationKey: 'TERMINATE',
    description: 'Verify loop invariants or base case satisfaction to halt execution.',
    effectText: 'Halts algorithm successfully. Deals 30 DMG.',
    damage: 30,
    shield: 20,
    iconName: 'CheckSquare',
    flavorQuote: 'An algorithm without termination is an infinite prison.',
  },
];

export const CS_ENCOUNTERS: EncounterDefinition[] = [
  {
    id: 'cs_lvl_1',
    levelNumber: 1,
    levelTitle: 'The Sorting Inversion',
    subject: 'computerScience',
    topic: 'Sorting & Invariants',
    conceptName: 'Bubble & Two-Pointer Invariant',
    pathType: 'main',
    objective: 'Establish sorting invariants and restore ascending order to the buffer.',
    problemStatement: 'Restore order to the unsorted memory buffer: [5, 2, 8, 1]',
    initialEquationOrState: 'Array: [5, 2, 8, 1] | Inversions Detected: 3',
    targetState: 'Array: [1, 2, 5, 8] [SORTED & VERIFIED]',
    optimalSequence: ['INITIALIZE', 'COMPARE', 'SWAP', 'TERMINATE'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'INITIALIZE',
        resultingState: 'Pointers set: i=0, j=1 | array[0]=5, array[1]=2',
        explanation: 'Loop bounds established. Scanning first adjacent pair.',
        damageValue: 25,
      },
      {
        stepIndex: 1,
        operationKey: 'COMPARE',
        resultingState: 'Evaluated: 5 > 2 => TRUE (Inversion detected)',
        explanation: 'Identified out-of-order sequence needing swap.',
        damageValue: 30,
      },
      {
        stepIndex: 2,
        operationKey: 'SWAP',
        resultingState: 'Swapped: [2, 5, 8, 1] | Inversions remaining: 2',
        explanation: 'Adjacent elements swapped to satisfy monotonic ordering.',
        damageValue: 35,
      },
      {
        stepIndex: 3,
        operationKey: 'TERMINATE',
        resultingState: 'Array: [1, 2, 5, 8] [SORTED & VERIFIED]',
        explanation: 'Pass completed with zero remaining inversions.',
        damageValue: 30,
      },
    ],
    validCards: CS_STARTER_CARDS,
    misconceptions: [
      {
        triggerOperation: 'SWAP',
        atStepIndex: 0,
        diagnosisType: 'prerequisite_gap',
        title: 'Premature Swap without Comparison',
        diagnosisExplanation: 'Attempted to swap elements without comparing their values first.',
        enemyAdaptationName: 'Index Out of Bounds Shield',
        enemyAdaptationEffect: 'Deploys a 25-point defensive ward.',
        repairConcept: 'Two-Pointer Invariants',
        echoVaultId: 'vault_cs_invariants',
      },
    ],
    enemy: {
      name: 'Algorithmic Horror',
      title: 'Spawn of Unbounded Complexity',
      hp: 110,
      attack: 20,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Order is an illusion; entropy is the only invariant.',
    },
    rewardXp: 120,
    rewardMastery: 25,
    unlockedCard: {
      id: 'cs_binary_search',
      name: 'Binary Divide',
      cost: 1,
      subject: 'computerScience',
      rarity: 'rare',
      operationKey: 'COMPARE',
      description: 'Halve the search space instantly.',
      effectText: 'Deals 40 DMG & reduces enemy defense.',
      damage: 40,
      shield: 15,
      iconName: 'Cpu',
      flavorQuote: 'O(log n) slices through exponential beasts.',
    },
  },
  {
    id: 'cs_lvl_2',
    levelNumber: 2,
    levelTitle: 'The Monotonic Divide',
    subject: 'computerScience',
    topic: 'Binary Search & Partitioning',
    conceptName: 'Logarithmic Search & Monotonic Space',
    pathType: 'main',
    objective: 'Search the sorted buffer and locate the key index in O(log n) time.',
    problemStatement: 'Locate target key 11 within sorted memory buffer: [2, 4, 7, 11, 15]',
    initialEquationOrState: 'Buffer: [2, 4, 7, 11, 15] | Search Space: O(n)',
    targetState: 'Key 11 found at index 3 [O(log n) PROVEN]',
    optimalSequence: ['INITIALIZE', 'COMPARE', 'TERMINATE'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'INITIALIZE',
        resultingState: 'Pointers set: low=0, high=4, mid=2 (arr[mid]=7)',
        explanation: 'Established search boundaries over monotonic array.',
        damageValue: 35,
      },
      {
        stepIndex: 1,
        operationKey: 'COMPARE',
        resultingState: 'Evaluated: target 11 > 7 => low = mid + 1 = 3',
        explanation: 'Halved search space using monotonic comparison predicate.',
        damageValue: 45,
      },
      {
        stepIndex: 2,
        operationKey: 'TERMINATE',
        resultingState: 'Target 11 identified at index 3! [O(log n) EFFICIENCY]',
        explanation: 'Logarithmic search terminated with exact key match.',
        damageValue: 40,
      },
    ],
    validCards: CS_STARTER_CARDS,
    misconceptions: [],
    enemy: {
      name: 'Logarithmic Sentinel',
      title: 'Guardian of the Monotonic Line',
      hp: 120,
      attack: 22,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Linear scans perish in my logarithmic labyrinth.',
    },
    rewardXp: 170,
    rewardMastery: 30,
  },
  {
    id: 'cs_lvl_3',
    levelNumber: 3,
    levelTitle: 'The Inversion Purge',
    subject: 'computerScience',
    topic: 'Sorting & Invariant Elimination',
    conceptName: 'Partitioning & Sorting Invariants',
    pathType: 'main',
    objective: 'Partition elements around the pivot to satisfy quicksort invariants.',
    problemStatement: 'Partition memory slice around pivot value 5: [8, 3, 5, 2, 7]',
    initialEquationOrState: 'Slice: [8, 3, 5, 2, 7] | Pivot: 5',
    targetState: 'Partitioned: [3, 2, 5, 8, 7] [PIVOT INVARIANT MET]',
    optimalSequence: ['INITIALIZE', 'COMPARE', 'SWAP', 'TERMINATE'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'INITIALIZE',
        resultingState: 'Pivot locked at 5 | Left & right pointers initialized',
        explanation: 'Initialized partition indices at array extremities.',
        damageValue: 30,
      },
      {
        stepIndex: 1,
        operationKey: 'COMPARE',
        resultingState: 'Scanned 8 > 5 and 2 < 5 => Inversion detected across pivot',
        explanation: 'Comparison identified elements on wrong sides of partition.',
        damageValue: 35,
      },
      {
        stepIndex: 2,
        operationKey: 'SWAP',
        resultingState: 'Swapped 8 and 2 => [2, 3, 5, 8, 7]',
        explanation: 'Transposed inverted elements across the pivot boundary.',
        damageValue: 40,
      },
      {
        stepIndex: 3,
        operationKey: 'TERMINATE',
        resultingState: 'Partition confirmed: Left ≤ 5 ≤ Right [SORT INVARIANT PROVEN]',
        explanation: 'All elements correctly segregated relative to pivot.',
        damageValue: 35,
      },
    ],
    validCards: CS_STARTER_CARDS,
    misconceptions: [],
    enemy: {
      name: 'Partition Fiend',
      title: 'Render of Memory Slices',
      hp: 130,
      attack: 24,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Unsorted chaos breeds entropy. Prove your partition!',
    },
    rewardXp: 210,
    rewardMastery: 35,
  },
  {
    id: 'cs_lvl_4',
    levelNumber: 4,
    levelTitle: 'The Memoized Cache',
    subject: 'computerScience',
    topic: 'Dynamic Programming & Memoization',
    conceptName: 'Overlapping Subproblems & Memoization',
    pathType: 'main',
    objective: 'Compute the 6th Fibonacci number using memoized subproblem transitions.',
    problemStatement: 'Compute Fibonacci Fib(6) without exponential tree explosion.',
    initialEquationOrState: 'Fib(6) => Tree size: 2⁵ operations',
    targetState: 'Fib(6) = 8 [O(n) OPTIMAL]',
    optimalSequence: ['INITIALIZE', 'MEMOIZE', 'TERMINATE'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'INITIALIZE',
        resultingState: 'DP Table initialized: memo[0]=0, memo[1]=1',
        explanation: 'Base cases populated in lookup cache.',
        damageValue: 35,
      },
      {
        stepIndex: 1,
        operationKey: 'MEMOIZE',
        resultingState: 'Computed iteratively: memo[2..6] cached in O(n) steps',
        explanation: 'Reused subproblem solutions instead of recomputing.',
        damageValue: 55,
      },
      {
        stepIndex: 2,
        operationKey: 'TERMINATE',
        resultingState: 'Returned memo[6] = 8 with linear complexity.',
        explanation: 'Optimal computation finalized.',
        damageValue: 35,
      },
    ],
    validCards: CS_STARTER_CARDS,
    misconceptions: [],
    enemy: {
      name: 'Recursion Beast',
      title: 'Devourer of Call Stacks',
      hp: 140,
      attack: 24,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Branch after branch, your stack frames belong to me!',
    },
    rewardXp: 250,
    rewardMastery: 40,
  },
  {
    id: 'cs_boss',
    levelNumber: 5,
    levelTitle: 'The Turing Archon',
    subject: 'computerScience',
    topic: 'Algorithmic Singularity & Invariance',
    conceptName: 'The Turing Archon Boss',
    isBoss: true,
    pathType: 'main',
    objective: 'Synthesize optimal invariant transitions to halt the recursion.',
    problemStatement: 'Halt the infinite recursion and execute Turing singularity!',
    initialEquationOrState: 'Call Stack Depth: ∞ | Entropy: Critical',
    targetState: 'Halting Problem Neutralized [TURING VICTORY]',
    optimalSequence: ['INITIALIZE', 'COMPARE', 'MEMOIZE', 'TERMINATE'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'INITIALIZE',
        resultingState: 'Tape bounded: Invariants pinned to immutable state',
        explanation: 'Restricted infinite state transition space.',
        damageValue: 45,
      },
      {
        stepIndex: 1,
        operationKey: 'COMPARE',
        resultingState: 'State transition validated against halting predicate',
        explanation: 'Proved deterministic progress towards termination.',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'MEMOIZE',
        resultingState: 'State graph collapsed into optimal polynomial DAG',
        explanation: 'Neutralized exponential recursive explosion.',
        damageValue: 60,
      },
      {
        stepIndex: 3,
        operationKey: 'TERMINATE',
        resultingState: 'TAPE HALTED deterministically [TOTAL CS MASTERY]',
        explanation: 'The Algorithmic Abyss collapses into order.',
        damageValue: 55,
      },
    ],
    validCards: CS_STARTER_CARDS,
    misconceptions: [],
    enemy: {
      name: 'The Turing Archon',
      title: 'Archon of the Algorithmic Abyss',
      hp: 190,
      attack: 26,
      visualType: 'algorithmic_horror',
      flavorQuote: 'I am the unbounded tape! You cannot prove I will ever halt!',
    },
    rewardXp: 350,
    rewardMastery: 45,
  },
  // HIDDEN DIFFICULT PATH: THE CRUCIBLE OF COMPRESSION
  {
    id: 'cs_hidden_trial_1',
    levelNumber: 101,
    levelTitle: 'Trial 1: The Monotonic Crucible',
    subject: 'computerScience',
    topic: 'Arrays + Binary Search',
    conceptName: 'The Monotonic Crucible',
    pathType: 'hidden_trial',
    trialOrder: 1,
    compressedConcepts: ['cs_arrays_invariants', 'cs_binary_search'],
    fallbackMainPathLevelMap: {
      cs_arrays_invariants: 1,
      cs_binary_search: 2,
    },
    objective: 'Synthesize array boundary checks with binary search to find the inflection point.',
    problemStatement: 'Locate anomaly in rotated sorted array: [4, 5, 6, 7, 0, 1, 2]',
    initialEquationOrState: 'Rotated Array: [4, 5, 6, 7, 0, 1, 2] | Inflection unknown',
    targetState: 'Inflection index 4 located [MONOTONIC INVARIANT PROVEN]',
    optimalSequence: ['INITIALIZE', 'COMPARE', 'TERMINATE'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'INITIALIZE',
        resultingState: 'Bounds set: low=0, high=6, mid=3 (arr[mid]=7)',
        explanation: 'Boundaries established over rotated sorted array.',
        damageValue: 45,
      },
      {
        stepIndex: 1,
        operationKey: 'COMPARE',
        resultingState: 'Evaluated: arr[mid]=7 > arr[high]=2 => inflection in right half',
        explanation: 'Identified unsorted partition containing anomaly in O(log n).',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'TERMINATE',
        resultingState: 'Inflection index 4 located: arr[4]=0 [PROVEN]',
        explanation: 'Search converged on rotation anomaly.',
        damageValue: 55,
      },
    ],
    validCards: CS_STARTER_CARDS,
    misconceptions: [
      {
        triggerOperation: 'SWAP',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Mutation of Search Space',
        diagnosisExplanation: 'Attempted to swap elements in search space instead of narrowing boundaries.',
        enemyAdaptationName: 'Search Space Fragmentation',
        enemyAdaptationEffect: 'Increases enemy shield.',
        repairConcept: 'Binary Search Monotonicity',
        echoVaultId: 'vault_cs_invariants',
      },
    ],
    enemy: {
      name: 'Monotonic Wyrm',
      title: 'Disrupter of Ordered Sequences',
      hp: 145,
      attack: 24,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Sorted assumptions shatter when the array rotates!',
    },
    rewardXp: 240,
    rewardMastery: 35,
  },
  {
    id: 'cs_hidden_trial_2',
    levelNumber: 102,
    levelTitle: 'Trial 2: The Optimal Substructure',
    subject: 'computerScience',
    topic: 'Sorting + Dynamic Programming',
    conceptName: 'The Optimal Substructure',
    pathType: 'hidden_trial',
    trialOrder: 2,
    compressedConcepts: ['cs_sorting', 'cs_dynamic_programming'],
    unlocksBossDirectly: true,
    fallbackMainPathLevelMap: {
      cs_sorting: 3,
      cs_dynamic_programming: 4,
    },
    prestigeRewards: {
      title: 'Entropy Compressor',
      relic: 'Quantum Cache',
      bonusXp: 300,
    },
    objective: 'Determine the Longest Increasing Subsequence length using optimal substructure.',
    problemStatement: 'Synthesize sorting invariants with memoized DP transitions: compute LIS length!',
    initialEquationOrState: 'Stream: [10, 9, 2, 5, 3, 7, 101, 18] | Subproblems: Uncached',
    targetState: 'LIS Length = 4 [OPTIMAL SUBSTRUCTURE PROVEN]',
    optimalSequence: ['COMPARE', 'MEMOIZE', 'TERMINATE'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'COMPARE',
        resultingState: 'Tested sequence predicates: 2 < 3 < 7 < 18',
        explanation: 'Extracted monotonic subsequence invariant.',
        damageValue: 50,
      },
      {
        stepIndex: 1,
        operationKey: 'MEMOIZE',
        resultingState: 'DP memo table updated: dp[i] = max(dp[j] + 1) in O(n log n)',
        explanation: 'Cached overlapping subsequence lengths to prevent exponential branching.',
        damageValue: 55,
      },
      {
        stepIndex: 2,
        operationKey: 'TERMINATE',
        resultingState: 'Global optimum locked: Max length 4 [COMPRESSION COMPLETE]',
        explanation: 'Combined sorting invariant and memoization proven.',
        damageValue: 60,
      },
    ],
    validCards: CS_STARTER_CARDS,
    misconceptions: [
      {
        triggerOperation: 'INITIALIZE',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Cache Invalidation during Transition',
        diagnosisExplanation: 'Resetting initialization during active memoization corrupts lookup tables.',
        enemyAdaptationName: 'Cache Eviction Penalty',
        enemyAdaptationEffect: 'Increases card costs.',
        repairConcept: 'Dynamic Programming Memoization',
        echoVaultId: 'vault_cs_invariants',
      },
    ],
    enemy: {
      name: 'Substructure Archon',
      title: 'Weaver of Optimal Paths',
      hp: 155,
      attack: 26,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Optimal substructure is the thread that holds all algorithms together!',
    },
    rewardXp: 300,
    rewardMastery: 40,
  },
];

export const CS_ECHO_VAULT: EchoDungeonDefinition = {
  id: 'vault_cs_invariants',
  subject: 'computerScience',
  title: 'The Recursion Vault',
  weaknessLabel: 'Pointer Initialization & State Check',
  misconceptionType: 'Blind Operation without State Invariant Validation',
  problemContext: 'Encountered array manipulation: [5, 2, 8, 1]',
  breakdownExplanation:
    'In algorithmic state transitions, modifications must be preceded by structural condition checks (such as ordering predicates). Blind modifications risk silent invariant violations or infinite recursion loops.',
  coreRule: 'Rule: Always INITIALIZE bounds and COMPARE elements before executing a state modification.',
  steps: [
    {
      stepNumber: 1,
      instruction: 'What must precede any element swap in a two-pointer pass?',
      options: [
        {
          label: 'Swap immediately without checking',
          operationKey: 'SWAP',
          isCorrect: false,
          feedback: 'Swapping without comparison might invert an already sorted pair!',
        },
        {
          label: 'Compare values at pointers: if arr[i] > arr[j]',
          operationKey: 'COMPARE',
          isCorrect: true,
          feedback: 'Correct! Only swap when an inversion is proven to exist.',
        },
      ],
    },
    {
      stepNumber: 2,
      instruction: 'After resolving inversions, what halts the algorithm?',
      options: [
        {
          label: 'Recurse infinitely without checking bounds',
          operationKey: 'RECURSE',
          isCorrect: false,
          feedback: 'Continuing after sorted order is achieved wastes cycles and triggers stack overflow.',
        },
        {
          label: 'Terminate when no inversions remain during a complete pass',
          operationKey: 'TERMINATE',
          isCorrect: true,
          feedback: 'Exact! The sorted invariant is established, proving algorithm completion.',
        },
      ],
    },
  ],
  rewardMastery: 25,
};

export const CS_SUBJECT_INFO: SubjectInfo = {
  id: 'computerScience',
  name: 'Computer Science',
  realmName: 'The Algorithmic Abyss',
  realmDescription: 'A glowing matrix of digital circuitry where recursion leaks and infinite loops threaten reality.',
  themeColor: '#3b82f6',
  accentColor: '#60a5fa',
  secondaryColor: '#1d4ed8',
  iconName: 'Cpu',
  storyIntro: {
    title: 'Descent into the Algorithmic Abyss',
    narration: [
      'In the digital depths of the Spire, rogue algorithms run without halting conditions.',
      'Memory leeches siphon bandwidth, while recursive beasts multiply exponentially.',
      'Your cards represent the fundamental operations of Turing completeness: initialization, comparison, and dynamic memory.',
    ],
    conceptCardIntro: [
      {
        cardName: 'INITIALIZE',
        quote: 'Establish loop bounds and state invariants before venturing into computation.',
        role: 'Setup & Defense',
      },
      {
        cardName: 'COMPARE',
        quote: 'Inspect states to uncover truth and expose inversions.',
        role: 'Analysis & Draw',
      },
      {
        cardName: 'SWAP',
        quote: 'Transpose elements to enforce minimal entropy.',
        role: 'Strike & Correction',
      },
      {
        cardName: 'TERMINATE',
        quote: 'Halt execution with deterministic proof of correctness.',
        role: 'Finisher & Proof',
      },
    ],
  },
  levels: [
    {
      id: 'cs_lvl_1',
      levelNumber: 1,
      title: 'The Sorting Inversion',
      topic: 'Sorting & Invariants',
      isBoss: false,
      pathType: 'main',
    },
    {
      id: 'cs_lvl_2',
      levelNumber: 2,
      title: 'The Monotonic Divide',
      topic: 'Binary Search & Partitioning',
      isBoss: false,
      pathType: 'main',
      requiredCompletedLevel: 1,
    },
    {
      id: 'cs_lvl_3',
      levelNumber: 3,
      title: 'The Inversion Purge',
      topic: 'Sorting & Invariant Elimination',
      isBoss: false,
      pathType: 'main',
      requiredCompletedLevel: 2,
    },
    {
      id: 'cs_lvl_4',
      levelNumber: 4,
      title: 'The Memoized Cache',
      topic: 'Dynamic Programming & Memoization',
      isBoss: false,
      pathType: 'main',
      requiredCompletedLevel: 3,
    },
    {
      id: 'cs_boss',
      levelNumber: 5,
      title: 'The Turing Archon',
      topic: 'Algorithmic Singularity Boss',
      isBoss: true,
      pathType: 'main',
      requiredCompletedLevel: 4,
    },
    // The Crucible of Compression (Hidden Path)
    {
      id: 'cs_hidden_trial_1',
      levelNumber: 101,
      title: 'The Monotonic Crucible',
      topic: 'Arrays + Binary Search',
      isBoss: false,
      pathType: 'hidden_trial',
      trialOrder: 1,
      compressedConcepts: ['cs_arrays_invariants', 'cs_binary_search'],
      requiredCompletedLevel: 1,
    },
    {
      id: 'cs_hidden_trial_2',
      levelNumber: 102,
      title: 'The Optimal Substructure',
      topic: 'Sorting + Dynamic Programming',
      isBoss: false,
      pathType: 'hidden_trial',
      trialOrder: 2,
      compressedConcepts: ['cs_sorting', 'cs_dynamic_programming'],
      requiredCompletedLevel: 101,
    },
  ],
};
