import { EncounterDefinition } from '../types/curriculum';
import { Card } from '../types/game';
import { DSA_STARTER_CARDS } from './dataStructuresAlgorithms';

function getValidCards(requiredOps: string[]): Card[] {
  const map = new Map<string, Card>();
  for (const op of requiredOps) {
    const card = DSA_STARTER_CARDS.find(c => c.operationKey === op);
    if (card) map.set(card.id, card);
  }
  const defaultOps = [
    'BOUND_ASYMPTOTIC',
    'VERIFY_INVARIANT',
    'IDENTIFY_DOMINANT',
    'COUNT_OPERATIONS',
    'TRACE_ARRAY',
    'CHECK_TREE',
    'DIVIDE_CONQUER',
    'BACKTRACK_SEARCH',
    'COMPUTE_BOUND',
    'FORMULATE_STATE',
    'DEFINE_RECURRENCE',
    'RELAX_EDGE',
    'VERIFY_CERTIFICATE',
    'CONSTRUCT_REDUCTION',
    'MAP_GADGET',
    'INVERT_COMPLEMENT',
    'BOUND_APPROXIMATION_RATIO',
  ];
  let added = 0;
  const targetDistractors = requiredOps.length >= 5 ? 2 : 3;
  for (const op of defaultOps) {
    if (!requiredOps.includes(op)) {
      const card = DSA_STARTER_CARDS.find(c => c.operationKey === op);
      if (card && !map.has(card.id)) {
        map.set(card.id, card);
        added++;
        if (added >= targetDistractors) break;
      }
    }
  }
  return Array.from(map.values());
}

export const DSA_HIDDEN_TRIALS: EncounterDefinition[] = [
  // -------------------------------------------------------------------------
  // TRIAL 1 (Level 101): Complexity Convergence
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd1',
    levelNumber: 101,
    levelTitle: 'Trial 1: The Complexity Convergence',
    subject: 'data_structures_algorithms',
    topic: 'Operation Counting + Asymptotics + Case Distributions',
    conceptName: 'Complexity Convergence',
    pathType: 'hidden_trial',
    trialOrder: 1,
    compressedConcepts: ['dsa_asymptotics', 'dsa_case_analysis'],
    fallbackMainPathLevelMap: {
      dsa_asymptotics: 1,
      dsa_case_analysis: 3,
    },
    objective: 'Synthesize exact operation counts across worst and average cases to establish tight asymptotic Theta bounds.',
    problemStatement: 'Partitioned search block: T(n) = sum_{i=1}^n (c * i) in worst-case, expected T_avg(n) = n(n+1)/4. Synthesize case limits into Theta(n^2).',
    initialEquationOrState: 'Worst: sum(c*i) | Avg: n(n+1)/4 | Asymptotic Class: ?',
    targetState: 'Theta(n^2) Quadratic Bound Verified [CONVERGENCE PROVEN]',
    correctAnswer: 'Theta(n^2)',
    optimalSequence: ['COUNT_OPERATIONS', 'ANALYZE_CASES', 'BOUND_ASYMPTOTIC', 'VERIFY_INVARIANT'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'COUNT_OPERATIONS',
        resultingState: 'Evaluated summation: sum_{i=1}^n c*i = c * n(n+1)/2 = (c/2)n^2 + (c/2)n.',
        explanation: 'Closed form summation of arithmetic progression calculated exactly.',
        damageValue: 40,
      },
      {
        stepIndex: 1,
        operationKey: 'ANALYZE_CASES',
        resultingState: 'Compared cases: Worst = (c/2)n^2, Average = (1/4)n^2. Both asymptotically quadratic.',
        explanation: 'Differentiated input distributions and verified leading quadratic term in all cases.',
        damageValue: 45,
      },
      {
        stepIndex: 2,
        operationKey: 'BOUND_ASYMPTOTIC',
        resultingState: 'Constructed witness pair: c1=1/4, c2=c/2, n0=2 such that c1*n^2 <= T(n) <= c2*n^2.',
        explanation: 'Formal definition of Theta(n^2) satisfied by sandwich inequalities.',
        damageValue: 50,
      },
      {
        stepIndex: 3,
        operationKey: 'VERIFY_INVARIANT',
        resultingState: 'Theta(n^2) Quadratic Bound Verified [CONVERGENCE PROVEN]',
        explanation: 'Proved exact quadratic convergence across all non-degenerate input permutations.',
        damageValue: 45,
      },
    ],
    validCards: getValidCards(['COUNT_OPERATIONS', 'ANALYZE_CASES', 'BOUND_ASYMPTOTIC', 'VERIFY_INVARIANT', 'EXPAND_RECURRENCE']),
    misconceptions: [
      {
        triggerOperation: 'EXPAND_RECURRENCE',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Iterative vs Recurrence Confusion',
        diagnosisExplanation: 'Non-recursive arithmetic summations are evaluated by closed-form formulas, not recurrence tree unrolling.',
        enemyAdaptationName: 'Recurrence Disruption',
        enemyAdaptationEffect: 'The Hydra deflects recursive expansions; next card cost +1 Energy.',
        repairConcept: 'Summations follow closed-form arithmetic sum identities.',
        echoVaultId: 'vault_dsa_asymptotics',
      },
      {
        triggerOperation: 'BOUND_ASYMPTOTIC',
        atStepIndex: 0,
        diagnosisType: 'conceptual_misconception',
        title: 'Premature Asymptotic Bound',
        diagnosisExplanation: 'You cannot assert an asymptotic bound before counting discrete operations.',
        enemyAdaptationName: 'Premature Bound Ward',
        enemyAdaptationEffect: 'The Hydra raises an impenetrable asymptotic shield.',
        repairConcept: 'Count discrete elementary operations first.',
        echoVaultId: 'vault_dsa_asymptotics',
      },
      {
        triggerOperation: 'VERIFY_INVARIANT',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Premature Verification',
        diagnosisExplanation: 'Verification must confirm established bounds, not precede case analysis.',
        enemyAdaptationName: 'Verification Shock',
        enemyAdaptationEffect: 'The Hydra retaliates against ungrounded verification.',
        repairConcept: 'Differentiate best, worst, and average cases before verifying.',
        echoVaultId: 'vault_dsa_asymptotics',
      },
    ],
    enemy: {
      name: 'The Convergence Hydra',
      title: 'Disrupter of Asymptotic Limits',
      hp: 220,
      attack: 28,
      visualType: 'algorithmic_horror',
      flavorQuote: 'When bounds diverge, infinite operations consume the runtime!',
    },
    rewardXp: 260,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 2 (Level 102): Recurrence Crucible
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd2',
    levelNumber: 102,
    levelTitle: 'Trial 2: The Recurrence Crucible',
    subject: 'data_structures_algorithms',
    topic: 'Recurrence Trees + Master Theorem + Substitution Induction',
    conceptName: 'Recurrence Crucible',
    pathType: 'hidden_trial',
    trialOrder: 2,
    compressedConcepts: ['dsa_recurrences', 'dsa_master_theorem'],
    fallbackMainPathLevelMap: {
      dsa_recurrences: 7,
      dsa_master_theorem: 10,
    },
    objective: 'Synthesize recurrence unrolling with Master Theorem Case 2 and substitution induction.',
    problemStatement: 'Solve T(n) = 2T(n/2) + O(n). Unroll recursive branches, classify via Master Theorem, and inductively verify Theta(n log n).',
    initialEquationOrState: 'T(n) = 2T(n/2) + cn | a=2, b=2, f(n)=cn | Solution: ?',
    targetState: 'T(n) = Theta(n log n) Inductively Proven [CRUCIBLE COMPLETE]',
    correctAnswer: 'T(n) = Theta(n log n)',
    optimalSequence: ['EXPAND_RECURRENCE', 'APPLY_MASTER_THEOREM', 'INDUCTIVE_STEP', 'VERIFY_INVARIANT'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'EXPAND_RECURRENCE',
        resultingState: 'Unrolled tree: Level k work = 2^k * c(n/2^k) = cn. Total depth = log2(n).',
        explanation: 'Each tree level performs exactly cn work across log2(n) levels.',
        damageValue: 45,
      },
      {
        stepIndex: 1,
        operationKey: 'APPLY_MASTER_THEOREM',
        resultingState: 'Classified: n^{log_b a} = n^1 = Theta(f(n)). Satisfies Master Theorem Case 2.',
        explanation: 'Critical exponent log2(2)=1 matches work per subproblem cn, producing n log n.',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'INDUCTIVE_STEP',
        resultingState: 'Substitution hypothesis: T(n) <= d * n log n - c*n. Inductive step holds for d >= c.',
        explanation: 'Inductive substitution verified without boundary leak.',
        damageValue: 50,
      },
      {
        stepIndex: 3,
        operationKey: 'VERIFY_INVARIANT',
        resultingState: 'T(n) = Theta(n log n) Inductively Proven [CRUCIBLE COMPLETE]',
        explanation: 'Proven asymptotically tight for divide-and-conquer recurrences.',
        damageValue: 45,
      },
    ],
    validCards: getValidCards(['EXPAND_RECURRENCE', 'APPLY_MASTER_THEOREM', 'INDUCTIVE_STEP', 'VERIFY_INVARIANT', 'COUNT_OPERATIONS']),
    misconceptions: [
      {
        triggerOperation: 'COUNT_OPERATIONS',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Flat Iterative Count on Recurrence',
        diagnosisExplanation: 'Divide-and-conquer recurrences require recursive tree unrolling or substitution, not flat iterative operation counting.',
        enemyAdaptationName: 'Call Stack Collapse',
        enemyAdaptationEffect: 'The Revenant collapses flat loop counters; next card costs +1 Energy.',
        repairConcept: 'Unroll recurrence tree levels k=0..log(n).',
        echoVaultId: 'vault_dsa_asymptotics',
      },
      {
        triggerOperation: 'APPLY_MASTER_THEOREM',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Premature Master Theorem',
        diagnosisExplanation: 'You must expand or analyze recurrence parameters (a, b, f(n)) before applying the Master Theorem formula.',
        enemyAdaptationName: 'Parameter Distortion',
        enemyAdaptationEffect: 'The Revenant disrupts unverified recurrence parameters.',
        repairConcept: 'Expand recurrence to establish subproblem count and division factor.',
        echoVaultId: 'vault_dsa_asymptotics',
      },
      {
        triggerOperation: 'COUNT_OPERATIONS',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Master Case Mismatch',
        diagnosisExplanation: 'Divide-and-conquer recurrences with equal root and leaf work require Master Theorem Case 2 log-factor scaling.',
        enemyAdaptationName: 'Master Barrier',
        enemyAdaptationEffect: 'The Revenant erects a recurrence shield.',
        repairConcept: 'Compare f(n) with n^{log_b a}.',
        echoVaultId: 'vault_dsa_asymptotics',
      },
      {
        triggerOperation: 'VERIFY_INVARIANT',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'Premature Verification Before Induction',
        diagnosisExplanation: 'Substitution method requires completing the inductive step before asserting the final bound.',
        enemyAdaptationName: 'Inductive Breach',
        enemyAdaptationEffect: 'The Revenant retaliates against ungrounded asymptotic claims.',
        repairConcept: 'Perform inductive step to bound lower-order constants.',
        echoVaultId: 'vault_dsa_asymptotics',
      },
    ],
    enemy: {
      name: 'The Recursive Revenant',
      title: 'Devourer of Call Stacks',
      hp: 230,
      attack: 29,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Infinite self-invocation without base termination is your doom!',
    },
    rewardXp: 280,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 3 (Level 103): Linear Buffer Fusion
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd3',
    levelNumber: 103,
    levelTitle: 'Trial 3: The Linear Buffer Fusion',
    subject: 'data_structures_algorithms',
    topic: 'Circular Buffers + Double-Ended Queues + Dynamic Expansion',
    conceptName: 'Linear Buffer Fusion',
    pathType: 'hidden_trial',
    trialOrder: 3,
    compressedConcepts: ['dsa_arrays_buffers', 'dsa_deques'],
    fallbackMainPathLevelMap: {
      dsa_arrays_buffers: 11,
      dsa_deques: 14,
    },
    objective: 'Implement circular ring index wrapping and double-ended queue operations with amortized O(1) resizing.',
    problemStatement: 'A ring deque of capacity C=4 reaches full boundary. Front=3, Rear=2. Execute circular wrapping, double-ended mutation, and verify contiguous amortized invariants.',
    initialEquationOrState: 'Deque(C=4) | Front=3, Rear=2 | Operation: Wrap & Insert',
    targetState: 'Deque Invariant Verified: Amortized O(1) [BUFFER FUSED]',
    correctAnswer: 'Wrap: (idx + 1) % C, Amortized O(1)',
    optimalSequence: ['CIRCULAR_WRAP', 'DEQUE_INSERT', 'ACCESS_INDEX', 'VERIFY_INVARIANT'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'CIRCULAR_WRAP',
        resultingState: 'Front index advanced modulo capacity: newFront = (3 + 1) % 4 = 0.',
        explanation: 'Modulo arithmetic wraps pointer around fixed memory block seamlessly.',
        damageValue: 45,
      },
      {
        stepIndex: 1,
        operationKey: 'DEQUE_INSERT',
        resultingState: 'Element inserted at head. Buffer expands from 4 to 8 elements via geometric doubling.',
        explanation: 'Amortized cost analysis confirms geometric doubling costs only O(1) per insertion.',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'ACCESS_INDEX',
        resultingState: 'Direct logical index access mapped: Physical = (Front + k) % Capacity.',
        explanation: 'O(1) random lookup preserved despite ring rotation.',
        damageValue: 50,
      },
      {
        stepIndex: 3,
        operationKey: 'VERIFY_INVARIANT',
        resultingState: 'Deque Invariant Verified: Amortized O(1) [BUFFER FUSED]',
        explanation: 'Proved circular deque maintains constant-time boundaries and bounds memory waste.',
        damageValue: 45,
      },
    ],
    validCards: getValidCards(['CIRCULAR_WRAP', 'DEQUE_INSERT', 'ACCESS_INDEX', 'VERIFY_INVARIANT', 'PUSH_STACK']),
    misconceptions: [
      {
        triggerOperation: 'ACCESS_INDEX',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Unwrapped Buffer Access',
        diagnosisExplanation: 'Accessing ring buffer indices without modulo wrapping causes out-of-bounds corruption.',
        enemyAdaptationName: 'Index Overflow',
        enemyAdaptationEffect: 'The Sentinel traps unwrapped indices; next card costs +1 Energy.',
        repairConcept: 'Apply modulo capacity formula: (index + 1) % capacity.',
        echoVaultId: 'vault_dsa_rotations',
      },
      {
        triggerOperation: 'PUSH_STACK',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'LIFO Mutation on FIFO/Deque',
        diagnosisExplanation: 'Deques require bidirectional access; pushing strictly to a LIFO stack breaks the double-ended queue invariant.',
        enemyAdaptationName: 'Stack Constriction',
        enemyAdaptationEffect: 'The Sentinel constricts bidirectional pointers.',
        repairConcept: 'Use double-ended queue insertion (front/rear).',
        echoVaultId: 'vault_dsa_rotations',
      },
      {
        triggerOperation: 'VERIFY_INVARIANT',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Premature Invariant Check',
        diagnosisExplanation: 'Cannot verify contiguous buffer invariants before completing deque pointer updates.',
        enemyAdaptationName: 'Sentinel Ward',
        enemyAdaptationEffect: 'The Sentinel reflects ungrounded verification.',
        repairConcept: 'Complete all index insertions and wraparound before invariant check.',
        echoVaultId: 'vault_dsa_rotations',
      },
    ],
    enemy: {
      name: 'The Circular Sentinel',
      title: 'Warden of Index Wraps',
      hp: 235,
      attack: 29,
      visualType: 'algorithmic_horror',
      flavorQuote: 'One off-by-one modulo error overwrites all unread data!',
    },
    rewardXp: 290,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 4 (Level 104): Pointer Weaver
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd4',
    levelNumber: 104,
    levelTitle: 'Trial 4: The Pointer Weaver',
    subject: 'data_structures_algorithms',
    topic: 'Linked List Reversal + Floyd Cycle Detection + Stack Frames',
    conceptName: 'Pointer Weaver',
    pathType: 'hidden_trial',
    trialOrder: 4,
    compressedConcepts: ['dsa_linked_lists', 'dsa_stacks'],
    fallbackMainPathLevelMap: {
      dsa_linked_lists: 15,
      dsa_stacks: 12,
    },
    objective: 'Detect cyclic loops with fast/slow pointers, unwind stack frames, and reverse pointer sequences in-place.',
    problemStatement: 'Singly linked chain with potential tail cycle. Traverse via two pointers, store activation frames on stack, reverse in-place, and verify O(1) space.',
    initialEquationOrState: 'Chain: Head -> A -> B -> C -> B? | Pointers unaligned',
    targetState: 'Cycle Neutralized & Chain Inverted in O(n) Time, O(1) Space [WOVEN]',
    correctAnswer: 'Floyd Tortoise-Hare: fast=fast.next.next, slow=slow.next',
    optimalSequence: ['TRAVERSE_LIST', 'PUSH_STACK', 'LINK_NODES', 'VERIFY_INVARIANT'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'TRAVERSE_LIST',
        resultingState: 'Floyd traversal: slow advances 1 step, fast advances 2 steps. Collision at node B proves cycle.',
        explanation: 'Two-pointer phase detection establishes cycle presence in O(n) without hash sets.',
        damageValue: 45,
      },
      {
        stepIndex: 1,
        operationKey: 'PUSH_STACK',
        resultingState: 'Cycle broken at meeting point. Nodes pushed to activation frame to verify topological order.',
        explanation: 'Stack frames preserve reverse traversal sequence.',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'LINK_NODES',
        resultingState: 'Pointer inversion: curr.next redirected to prev. In-place 3-pointer swap completed.',
        explanation: 'Nodes linked in reverse order without heap allocation.',
        damageValue: 50,
      },
      {
        stepIndex: 3,
        operationKey: 'VERIFY_INVARIANT',
        resultingState: 'Cycle Neutralized & Chain Inverted in O(n) Time, O(1) Space [WOVEN]',
        explanation: 'Proved O(1) auxiliary space invariant with zero memory leaks.',
        damageValue: 45,
      },
    ],
    validCards: getValidCards(['TRAVERSE_LIST', 'PUSH_STACK', 'LINK_NODES', 'VERIFY_INVARIANT', 'ACCESS_INDEX']),
    misconceptions: [
      {
        triggerOperation: 'ACCESS_INDEX',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Non-Contiguous Lookup Violation',
        diagnosisExplanation: 'Linked lists do not support O(1) index access; pointers must be traversed sequentially.',
        enemyAdaptationName: 'Pointer Dissolution',
        enemyAdaptationEffect: 'The Weaver dissolves arbitrary index pointers; next card costs +1 Energy.',
        repairConcept: 'Use sequential pointer traversal (slow/fast pointers).',
        echoVaultId: 'vault_dsa_rotations',
      },
      {
        triggerOperation: 'LINK_NODES',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Premature Pointer Inversion',
        diagnosisExplanation: 'Inverting pointers while a cycle exists causes an infinite traversal loop; isolate the loop node first.',
        enemyAdaptationName: 'Cyclic Entanglement',
        enemyAdaptationEffect: 'The Weaver creates an endless cycle; next card costs +1 Energy.',
        repairConcept: 'Preserve frame sequence on stack before reversing pointer links.',
        echoVaultId: 'vault_dsa_rotations',
      },
      {
        triggerOperation: 'VERIFY_INVARIANT',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'Unverified Chain Inversion',
        diagnosisExplanation: 'Cannot verify O(1) space invariant before rewriting head and tail pointer references.',
        enemyAdaptationName: 'Memory Leak Surge',
        enemyAdaptationEffect: 'The Weaver retaliates against dangling pointer references.',
        repairConcept: 'Link all nodes in reverse order before verifying invariant.',
        echoVaultId: 'vault_dsa_rotations',
      },
    ],
    enemy: {
      name: 'The Phantom Weaver',
      title: 'Spinner of Cyclic Traps',
      hp: 240,
      attack: 30,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Pointers that point to their ancestors wander the abyss forever!',
    },
    rewardXp: 300,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 5 (Level 105): Graph Traversal Trial
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd5',
    levelNumber: 105,
    levelTitle: 'Trial 5: The Graph Traversal Trial',
    subject: 'data_structures_algorithms',
    topic: 'Adjacency Lists/Matrices + BFS Shortest Paths + DFS Cycle Detection + DAG Algorithm Selection',
    conceptName: 'Graph Traversal Trial',
    pathType: 'hidden_trial',
    trialOrder: 5,
    compressedConcepts: ['dsa_graphs', 'dsa_graph_traversal'],
    fallbackMainPathLevelMap: {
      dsa_graphs: 21,
      dsa_graph_traversal: 22,
    },
    objective: 'Synthesize optimal graph representation, BFS unweighted shortest path calculation, DFS back-edge cycle detection, and DAG algorithm selection.',
    problemStatement: 'Sparse directed network G = (V, E) with |V| = 1,000 and |E| = 2,500. Represent via adjacency list, execute BFS level-order frontier to compute unweighted shortest paths, and use DFS recursion stack to detect back-edges or select DAG topological ordering.',
    initialEquationOrState: 'Directed Graph G=(1000, 2500) | Unrepresented | Query: Shortest Path vs Cycle/DAG Selection',
    targetState: 'Graph Traversal Synthesized: BFS Levels, DFS Cycles & DAG Invariant Verified [GRAPH TRAVERSED]',
    correctAnswer: 'Adjacency list O(V + E) representation, BFS shortest path, DFS back-edge cycle detection',
    optimalSequence: ['REPRESENT_GRAPH', 'BFS_TRAVERSE', 'DFS_TRAVERSE', 'VERIFY_INVARIANT'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'REPRESENT_GRAPH',
        resultingState: 'Adjacency list initialized: Array of |V| linked lists allocated, consuming O(V + E) space instead of O(V^2) dense matrix waste.',
        explanation: 'Built compact sparse graph representation storing outgoing edges in O(V + E) memory.',
        damageValue: 50,
      },
      {
        stepIndex: 1,
        operationKey: 'BFS_TRAVERSE',
        resultingState: 'BFS FIFO frontier expanded: Levels 0, 1, 2 discovered. Unweighted geodesic distances proven in O(V + E).',
        explanation: 'BFS queue processing guarantees minimal hop count to every reachable node.',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'DFS_TRAVERSE',
        resultingState: 'DFS recursive descent completed: Discovered back-edge (u, v) pointing to ancestor on recursion call stack. Directed cycle classified.',
        explanation: 'DFS timestamping detects cycles via back-edges to gray ancestors.',
        damageValue: 55,
      },
      {
        stepIndex: 3,
        operationKey: 'VERIFY_INVARIANT',
        resultingState: 'Graph Traversal Synthesized: BFS Levels, DFS Cycles & DAG Invariant Verified [GRAPH TRAVERSED]',
        explanation: 'Graph traversal invariants rigorously confirmed across representation, reachability, and cycle analysis.',
        damageValue: 50,
      },
    ],
    alternativePaths: [
      {
        id: 'dsa_hidden_hd5_alt_dfs_first',
        name: 'Method B: DFS Cycle & DAG Invariant First',
        operations: ['REPRESENT_GRAPH', 'DFS_TRAVERSE', 'BFS_TRAVERSE', 'VERIFY_INVARIANT'],
        educationalMethod: 'DFS Cycle Classification Followed by BFS Reachability',
        difficulty: 2,
        completionCondition: 'Graph Traversal Synthesized: BFS Levels, DFS Cycles & DAG Invariant Verified [GRAPH TRAVERSED]',
        transformations: [
          {
            stepIndex: 0,
            operationKey: 'REPRESENT_GRAPH',
            resultingState: 'Adjacency list initialized: Array of |V| linked lists allocated in O(V + E) space.',
            explanation: 'Built compact sparse graph representation.',
            damageValue: 50,
          },
          {
            stepIndex: 1,
            operationKey: 'DFS_TRAVERSE',
            resultingState: 'DFS recursion descent executed: Classified tree vs back edges on call stack.',
            explanation: 'Audited graph for directed cycles via depth-first back-edge detection.',
            damageValue: 50,
          },
          {
            stepIndex: 2,
            operationKey: 'BFS_TRAVERSE',
            resultingState: 'BFS queue exploration executed: Layer-by-layer geodesic distances computed.',
            explanation: 'Calculated shortest unweighted paths from source.',
            damageValue: 55,
          },
          {
            stepIndex: 3,
            operationKey: 'VERIFY_INVARIANT',
            resultingState: 'Graph Traversal Synthesized: BFS Levels, DFS Cycles & DAG Invariant Verified [GRAPH TRAVERSED]',
            explanation: 'Dual traversal invariants verified across depth and breadth frontiers.',
            damageValue: 50,
          },
        ],
      },
      {
        id: 'dsa_hidden_hd5_alt_space_audit',
        name: 'Method C: Space Complexity Audit Route',
        operations: ['EVALUATE_SPACE', 'REPRESENT_GRAPH', 'BFS_TRAVERSE', 'VERIFY_INVARIANT'],
        educationalMethod: 'Asymptotic Space Audit followed by BFS Traversal',
        difficulty: 2,
        completionCondition: 'Graph Traversal Synthesized: BFS Levels, DFS Cycles & DAG Invariant Verified [GRAPH TRAVERSED]',
        transformations: [
          {
            stepIndex: 0,
            operationKey: 'EVALUATE_SPACE',
            resultingState: 'Space evaluated: Dense matrix requires V^2 = 1,000,000 cells vs list requiring V + E = 3,500 entries (99.6% savings).',
            explanation: 'Audited asymptotic space efficiency prior to constructing graph.',
            damageValue: 50,
          },
          {
            stepIndex: 1,
            operationKey: 'REPRESENT_GRAPH',
            resultingState: 'Adjacency list constructed based on space audit: O(V + E) memory confirmed.',
            explanation: 'Selected and instantiated adjacency list representation.',
            damageValue: 50,
          },
          {
            stepIndex: 2,
            operationKey: 'BFS_TRAVERSE',
            resultingState: 'BFS frontier traversed: Shortest hop levels mapped from root node.',
            explanation: 'Discovered reachable vertices in minimal hop distance.',
            damageValue: 55,
          },
          {
            stepIndex: 3,
            operationKey: 'VERIFY_INVARIANT',
            resultingState: 'Graph Traversal Synthesized: BFS Levels, DFS Cycles & DAG Invariant Verified [GRAPH TRAVERSED]',
            explanation: 'Space and traversal invariants verified.',
            damageValue: 50,
          },
        ],
      },
    ],
    validCards: getValidCards([
      'REPRESENT_GRAPH',
      'BFS_TRAVERSE',
      'DFS_TRAVERSE',
      'VERIFY_INVARIANT',
      'EVALUATE_SPACE',
      'TRACE_ARRAY',
      'PUSH_STACK',
      'DIVIDE_CONQUER',
      'RELAX_EDGE',
      'BST_SEARCH',
    ]),
    misconceptions: [
      {
        triggerOperation: 'TRACE_ARRAY',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Dense Matrix Allocation for Sparse Graph',
        diagnosisExplanation: 'Allocating an adjacency matrix on sparse graph G=(1000, 2500) wastes O(V²) = 1,000,000 cells. An adjacency list uses only O(V + E) memory.',
        enemyAdaptationName: 'Dense Fog Barrier',
        enemyAdaptationEffect: 'The Specter punishes dense quadratic allocations; next card costs +1 Energy.',
        repairConcept: 'Construct an adjacency list with O(V + E) space.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'BFS_TRAVERSE',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Traversal Before Graph Representation',
        diagnosisExplanation: 'Cannot initiate BFS traversal before the graph is represented in memory as an adjacency list or matrix.',
        enemyAdaptationName: 'Disjoint Void Ward',
        enemyAdaptationEffect: 'The Specter deflects traversal on unrepresented nodes; next card costs +1 Energy.',
        repairConcept: 'Represent the graph via adjacency list first.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'DFS_TRAVERSE',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'DFS Descent Before Graph Representation',
        diagnosisExplanation: 'Cannot execute DFS traversal before graph vertices and incident edges are represented in data structures.',
        enemyAdaptationName: 'Unlinked Abyss',
        enemyAdaptationEffect: 'The Specter collapses unrepresented paths; next card costs +1 Energy.',
        repairConcept: 'Represent graph via adjacency list before initiating traversal.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'PUSH_STACK',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'LIFO Stack Used for Breadth-First Shortest Path',
        diagnosisExplanation: 'Using a stack results in Depth-First Search, which does not guarantee unweighted shortest paths. A FIFO queue is required for BFS.',
        enemyAdaptationName: 'Depth Miasma',
        enemyAdaptationEffect: 'The Specter distorts shortest path calculations; next card costs +1 Energy.',
        repairConcept: 'Use a FIFO queue to explore vertices in level-order.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'DIVIDE_CONQUER',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Arbitrary Graph Partitioning',
        diagnosisExplanation: 'General graphs with cycles cannot be decomposed via naive divide-and-conquer without cut validation.',
        enemyAdaptationName: 'Topological Rupture',
        enemyAdaptationEffect: 'The Specter absorbs unpartitioned cuts; next card costs +1 Energy.',
        repairConcept: 'Use BFS or DFS traversal.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'RELAX_EDGE',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Weighted Relaxation on Unweighted Graph',
        diagnosisExplanation: 'Unweighted graphs achieve shortest paths in O(V + E) via BFS queue; weighted edge relaxation introduces unnecessary overhead.',
        enemyAdaptationName: 'Overhead Singularity',
        enemyAdaptationEffect: 'The Specter drags down over-engineered algorithms; next card costs +1 Energy.',
        repairConcept: 'Use unweighted BFS queue traversal for optimal O(V + E) performance.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'VERIFY_INVARIANT',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'Premature Invariant Verification',
        diagnosisExplanation: 'Cannot verify graph reachability and cycle status before completing DFS back-edge classification.',
        enemyAdaptationName: 'Back-Edge Feedback',
        enemyAdaptationEffect: 'The Specter shocks unclassified back-edges; next card costs +1 Energy.',
        repairConcept: 'Complete DFS cycle detection before verifying invariants.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'BST_SEARCH',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'BST Search on Cyclic Graph',
        diagnosisExplanation: 'Binary Search Tree operations require an acyclic tree with left < root < right ordering; general directed graphs lack BST key properties.',
        enemyAdaptationName: 'Cyclic Entanglement',
        enemyAdaptationEffect: 'The Specter repels ordered tree operations; next card costs +1 Energy.',
        repairConcept: 'Use graph search algorithms (BFS/DFS) designed for general topologies.',
        echoVaultId: 'vault_dsa_strategy',
      },
    ],
    enemy: {
      name: 'The Topological Phantom',
      title: 'Stalker of Cyclic Labyrinths',
      hp: 250,
      attack: 31,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Traverse without cycle detection, and you shall wander the recursive call stack for eternity!',
    },
    rewardXp: 310,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 6 (Level 106): Graph Traversal Synapse
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd6',
    levelNumber: 106,
    levelTitle: 'Trial 6: The Graph Traversal Synapse',
    subject: 'data_structures_algorithms',
    topic: 'Adjacency Lists + BFS Shortest Hops + DFS Back-Edge Cycles',
    conceptName: 'Graph Traversal Synapse',
    pathType: 'hidden_trial',
    trialOrder: 6,
    compressedConcepts: ['dsa_graphs', 'dsa_graph_traversal'],
    fallbackMainPathLevelMap: {
      dsa_graphs: 21,
      dsa_graph_traversal: 22,
    },
    objective: 'Construct compact graph representations and synthesize BFS level-order exploration with DFS back-edge cycle detection.',
    problemStatement: 'Graph G=(V,E) with |V|=8, |E|=12. Represent via adjacency list in O(V+E) space, traverse via BFS for shortest hop layers, then run DFS to classify tree edges and detect back-edges.',
    initialEquationOrState: 'Graph G=(8,12) | Unrepresented | Traversal: BFS & DFS',
    targetState: 'BFS Levels Mapped & DFS Cycle Classification Verified [SYNAPSE PROVEN]',
    correctAnswer: 'Back-edge to ancestor in DFS tree proves cycle',
    optimalSequence: ['REPRESENT_GRAPH', 'BFS_TRAVERSE', 'DFS_TRAVERSE', 'VERIFY_INVARIANT'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'REPRESENT_GRAPH',
        resultingState: 'Adjacency list initialized: O(V + E) memory allocated, avoiding O(V^2) dense matrix waste.',
        explanation: 'Compact sparse graph representation established.',
        damageValue: 45,
      },
      {
        stepIndex: 1,
        operationKey: 'BFS_TRAVERSE',
        resultingState: 'BFS queue exploration: Layered distance levels 0, 1, 2 discovered in non-decreasing order.',
        explanation: 'Queue-based FIFO search guarantees unweighted shortest path bounds.',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'DFS_TRAVERSE',
        resultingState: 'DFS recursive descent: Discovery/finish timestamps recorded. Back-edge (u, v) detected.',
        explanation: 'Back-edge connects vertex to an active ancestor on recursion stack, proving cycle existence.',
        damageValue: 55,
      },
      {
        stepIndex: 3,
        operationKey: 'VERIFY_INVARIANT',
        resultingState: 'BFS Levels Mapped & DFS Cycle Classification Verified [SYNAPSE PROVEN]',
        explanation: 'Topological and shortest-hop graph properties rigorously verified.',
        damageValue: 45,
      },
    ],
    validCards: getValidCards(['REPRESENT_GRAPH', 'BFS_TRAVERSE', 'DFS_TRAVERSE', 'VERIFY_INVARIANT', 'DIVIDE_CONQUER']),
    misconceptions: [
      {
        triggerOperation: 'BFS_TRAVERSE',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Traversal Without Adjacency Representation',
        diagnosisExplanation: 'Cannot traverse a graph before establishing its adjacency list or matrix structure.',
        enemyAdaptationName: 'Disjoint Void',
        enemyAdaptationEffect: 'The Nexus fractures unrepresented nodes; next card costs +1 Energy.',
        repairConcept: 'Represent graph via adjacency list before initiating traversal.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'DIVIDE_CONQUER',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Arbitrary Graph Partition',
        diagnosisExplanation: 'General graphs with cycles cannot be decomposed via naive divide-and-conquer without cut validation.',
        enemyAdaptationName: 'Topological Rupture',
        enemyAdaptationEffect: 'The Nexus collapses partitioned edges.',
        repairConcept: 'Use BFS shortest-path exploration with visited sets.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'VERIFY_INVARIANT',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'Premature Bipartite Invariant',
        diagnosisExplanation: 'Cannot verify 2-colorability or cycle detection before completing DFS back-edge classification.',
        enemyAdaptationName: 'Back-Edge Shock',
        enemyAdaptationEffect: 'The Nexus shocks unclassified back-edges.',
        repairConcept: 'Classify tree vs back edges via DFS before invariant verification.',
        echoVaultId: 'vault_dsa_strategy',
      },
    ],
    enemy: {
      name: 'The Meridian Behemoth',
      title: 'Stalker of Cyclic Labyrinths',
      hp: 250,
      attack: 31,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Enter the maze without back-edge detection, and you will loop through eternity!',
    },
    rewardXp: 320,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 7 (Level 107): Divide & Conquer Vanguard
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd7',
    levelNumber: 107,
    levelTitle: 'Trial 7: The Divide & Conquer Vanguard',
    subject: 'data_structures_algorithms',
    topic: 'Subproblem Decomposition + Partition Invariants + Decision Tree Bounds',
    conceptName: 'Divide & Conquer Vanguard',
    pathType: 'hidden_trial',
    trialOrder: 7,
    compressedConcepts: ['dsa_divide_conquer', 'dsa_sorting_bounds'],
    fallbackMainPathLevelMap: {
      dsa_divide_conquer: 25,
      dsa_sorting_bounds: 27,
    },
    objective: 'Synthesize optimal pivot selection with recursive subproblem partitioning and comparison decision tree lower bounds.',
    problemStatement: 'Analyze sorting lower bounds: Compare recursive halves, partition via Lomuto/Hoare invariant, and prove any comparison sort must make Omega(n log n) comparisons.',
    initialEquationOrState: 'Sorting Array: N elements | Lower Bound: ? | Method: Divide & Partition',
    targetState: 'Omega(n log n) Information-Theoretic Lower Bound Verified [VANGUARD ESTABLISHED]',
    correctAnswer: 'log(n!) = Omega(n log n) comparisons',
    optimalSequence: ['DIVIDE_CONQUER', 'PARTITION_PIVOT', 'BOUND_DECISION_TREE', 'VERIFY_INVARIANT'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'DIVIDE_CONQUER',
        resultingState: 'Problem split into independent balanced subproblems of size n/2 in O(1) divide time.',
        explanation: 'Independent subproblem generation established.',
        damageValue: 50,
      },
      {
        stepIndex: 1,
        operationKey: 'PARTITION_PIVOT',
        resultingState: 'Pivot partition invariant: elements <= pivot on left, elements > pivot on right in O(n) scan.',
        explanation: 'Linear-time partition places pivot at its permanent sorted location.',
        damageValue: 55,
      },
      {
        stepIndex: 2,
        operationKey: 'BOUND_DECISION_TREE',
        resultingState: 'Decision tree has n! leaves. Tree height h >= log2(n!) >= n log2(n/e) = Omega(n log n).',
        explanation: 'Information-theoretic lower bound proves no comparison sort can beat n log n.',
        damageValue: 55,
      },
      {
        stepIndex: 3,
        operationKey: 'VERIFY_INVARIANT',
        resultingState: 'Omega(n log n) Information-Theoretic Lower Bound Verified [VANGUARD ESTABLISHED]',
        explanation: 'Proved asymptotic optimality of comparison-based divide-and-conquer sorts.',
        damageValue: 50,
      },
    ],
    validCards: getValidCards(['DIVIDE_CONQUER', 'PARTITION_PIVOT', 'BOUND_DECISION_TREE', 'VERIFY_INVARIANT', 'BACKTRACK_SEARCH']),
    misconceptions: [
      {
        triggerOperation: 'PARTITION_PIVOT',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Partitioning Without Subproblem Decomposition',
        diagnosisExplanation: 'Quickselect/Quicksort requires establishing subproblem bounds [low..high] before pivoting.',
        enemyAdaptationName: 'Boundary Disarray',
        enemyAdaptationEffect: 'The Chimera scrambles array boundaries; next card costs +1 Energy.',
        repairConcept: 'Decompose problem into recursive subarray bounds.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'BACKTRACK_SEARCH',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Exhaustive Permutation Sorting',
        diagnosisExplanation: 'Sorting by generating all n! permutations runs in factorial time; comparison partitioning requires O(n log n).',
        enemyAdaptationName: 'Factorial Explosion',
        enemyAdaptationEffect: 'The Chimera summons factorial runtime drag.',
        repairConcept: 'Partition around pivot element in linear time.',
        echoVaultId: 'vault_dsa_strategy',
      },
      {
        triggerOperation: 'VERIFY_INVARIANT',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'Premature Lower Bound Claim',
        diagnosisExplanation: 'Cannot assert Omega(n log n) optimality without decision tree leaf height lower bound proof.',
        enemyAdaptationName: 'Comparison Ward',
        enemyAdaptationEffect: 'The Chimera blocks unproven lower-bound claims.',
        repairConcept: 'Bound decision tree depth using log2(n!) = Omega(n log n).',
        echoVaultId: 'vault_dsa_strategy',
      },
    ],
    enemy: {
      name: 'The Partition Colossus',
      title: 'Crusher of Unbalanced Splits',
      hp: 255,
      attack: 31,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Pick the wrong pivot, and your logarithmic dreams collapse into quadratic ruin!',
    },
    rewardXp: 330,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 8 (Level 108): Backtrack & Prune Spire
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd8',
    levelNumber: 108,
    levelTitle: 'Trial 8: The Backtrack & Prune Spire',
    subject: 'data_structures_algorithms',
    topic: 'State-Space Trees + Branch & Bound Pruning + Candidate Verification',
    conceptName: 'Backtrack & Prune Spire',
    pathType: 'hidden_trial',
    trialOrder: 8,
    compressedConcepts: ['dsa_backtracking', 'dsa_branch_bound'],
    fallbackMainPathLevelMap: {
      dsa_backtracking: 28,
      dsa_branch_bound: 30,
    },
    objective: 'Explore combinatorial search spaces via depth-first backtracking while pruning sub-optimal branches with bounding functions.',
    problemStatement: 'Combinatorial 0/1 Knapsack problem with capacity W=15. Formulate state-space search, calculate fractional bounding upper bound, prune non-promising subtrees, and verify optimal assignment.',
    initialEquationOrState: 'State Tree: 2^n configurations | Capacity W=15 | Bound: Fractional Relaxation',
    targetState: 'Sub-Optimal Branches Pruned & Global Optimum Guaranteed [SPIRE CONQUERED]',
    correctAnswer: 'Prune when UpperBound(node) <= BestValueSoFar',
    optimalSequence: ['BACKTRACK_SEARCH', 'COMPUTE_BOUND', 'PRUNE_BOUND', 'VERIFY_INVARIANT'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'BACKTRACK_SEARCH',
        resultingState: 'State space tree traversed depth-first: partial candidate vectors (x1, x2, ..., xk) constructed.',
        explanation: 'Incremental candidate expansion saves exponential state space.',
        damageValue: 50,
      },
      {
        stepIndex: 1,
        operationKey: 'COMPUTE_BOUND',
        resultingState: 'Fractional relaxation bound computed: upper bound on remaining capacity evaluated greedily.',
        explanation: 'Calculated upper bound on best possible value obtainable in current subtree.',
        damageValue: 55,
      },
      {
        stepIndex: 2,
        operationKey: 'PRUNE_BOUND',
        resultingState: 'Pruned 85% of state tree: upper bound is strictly less than incumbent best solution.',
        explanation: 'Branch-and-bound eliminates provably sub-optimal permutations without full expansion.',
        damageValue: 55,
      },
      {
        stepIndex: 3,
        operationKey: 'VERIFY_INVARIANT',
        resultingState: 'Sub-Optimal Branches Pruned & Global Optimum Guaranteed [SPIRE CONQUERED]',
        explanation: 'Guaranteed exact global optimality with exponentially reduced node expansions.',
        damageValue: 50,
      },
    ],
    validCards: getValidCards(['BACKTRACK_SEARCH', 'COMPUTE_BOUND', 'PRUNE_BOUND', 'VERIFY_INVARIANT', 'TABULATE_BOTTOM_UP']),
    misconceptions: [
      {
        triggerOperation: 'TABULATE_BOTTOM_UP',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Premature DP State Allocation',
        diagnosisExplanation: 'NP-hard combinatorial problems cannot be naively tabulated without polynomial state-space proof; branch-and-bound pruning is required.',
        enemyAdaptationName: 'State Explosion',
        enemyAdaptationEffect: 'The Behemoth overflows memoization memory; next card costs +1 Energy.',
        repairConcept: 'Formulate state-space search tree with bounding functions.',
        echoVaultId: 'vault_dsa_optimization',
      },
      {
        triggerOperation: 'PRUNE_BOUND',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Pruning Without Estimating Bound',
        diagnosisExplanation: 'Cannot prune a search branch before computing its upper/lower optimistic bound against the best-known incumbent.',
        enemyAdaptationName: 'Blind Cut',
        enemyAdaptationEffect: 'The Behemoth deflects unjustified pruning cuts.',
        repairConcept: 'Compute optimistic dual/relaxation bound first.',
        echoVaultId: 'vault_dsa_optimization',
      },
      {
        triggerOperation: 'VERIFY_INVARIANT',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'Unproven Optimality Verification',
        diagnosisExplanation: 'Cannot verify global optimality while active branches exceed the current incumbent solution.',
        enemyAdaptationName: 'Suboptimal Encroachment',
        enemyAdaptationEffect: 'The Behemoth retaliates against unpruned branch leakage.',
        repairConcept: 'Prune all dominated branches where bound <= best-known cost.',
        echoVaultId: 'vault_dsa_optimization',
      },
    ],
    enemy: {
      name: 'The Combinatorial Chimera',
      title: 'Spawn of 2^N Possibilities',
      hp: 260,
      attack: 32,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Without bounds, you will wander through two to the N branches until the sun burns out!',
    },
    rewardXp: 340,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 9 (Level 109): Greedy Horizon
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd9',
    levelNumber: 109,
    levelTitle: 'Trial 9: The Greedy Horizon',
    subject: 'data_structures_algorithms',
    topic: 'Greedy-Choice Property + Optimal Prefix Trees + Matroid Independence',
    conceptName: 'Greedy Horizon',
    pathType: 'hidden_trial',
    trialOrder: 9,
    compressedConcepts: ['dsa_greedy_choice', 'dsa_mst'],
    fallbackMainPathLevelMap: {
      dsa_greedy_choice: 32,
      dsa_mst: 33,
    },
    objective: 'Prove greedy choice property and optimal substructure across Huffman tree encoding and Kruskal/Prim Minimum Spanning Trees.',
    problemStatement: 'Verify matroid exchange property: Merge lowest frequency symbols into prefix tree, sort weighted edges, select min-weight crossing edges without cycles, and prove global optimality.',
    initialEquationOrState: 'Frequencies & Edges | Greedy Choice: Locally Optimal | Global: ?',
    targetState: 'Greedy Choice Property Proven Globally Optimal [HORIZON ATTAINED]',
    correctAnswer: 'Cut Property: Min-weight crossing edge belongs to every MST',
    optimalSequence: ['SELECT_STRATEGY', 'MERGE_FREQUENCIES', 'FIND_UNION_CYCLE', 'VERIFY_INVARIANT'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'SELECT_STRATEGY',
        resultingState: 'Greedy choice property formulated: locally optimal choice at each step leads to global optimum.',
        explanation: 'Established matroid independence and cut property validity.',
        damageValue: 50,
      },
      {
        stepIndex: 1,
        operationKey: 'MERGE_FREQUENCIES',
        resultingState: 'Min-heap extraction: two lowest-frequency symbols merged repeatedly into optimal prefix tree.',
        explanation: 'Huffman algorithm produces minimal expected code length sum(f_i * d_i).',
        damageValue: 55,
      },
      {
        stepIndex: 2,
        operationKey: 'FIND_UNION_CYCLE',
        resultingState: 'Disjoint-set union-find: added min-weight edge (u, v) with path compression, rejecting cycle.',
        explanation: 'Near constant-time inverse Ackermann alpha(V) cycle avoidance.',
        damageValue: 60,
      },
      {
        stepIndex: 3,
        operationKey: 'VERIFY_INVARIANT',
        resultingState: 'Greedy Choice Property Proven Globally Optimal [HORIZON ATTAINED]',
        explanation: 'Proved greedy exchange argument yields absolute minimum total weight.',
        damageValue: 50,
      },
    ],
    validCards: getValidCards(['SELECT_STRATEGY', 'MERGE_FREQUENCIES', 'FIND_UNION_CYCLE', 'VERIFY_INVARIANT', 'EXPAND_RECURRENCE']),
    misconceptions: [
      {
        triggerOperation: 'MERGE_FREQUENCIES',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Merging Before Sorting/Strategy Selection',
        diagnosisExplanation: 'Greedy choice property requires ordering elements by key weight or frequency before merging.',
        enemyAdaptationName: 'Unsorted Inversion',
        enemyAdaptationEffect: 'The Colossus scatters unsorted elements; next card costs +1 Energy.',
        repairConcept: 'Select greedy ordering strategy (min-heap / sorted weights).',
        echoVaultId: 'vault_dsa_optimization',
      },
      {
        triggerOperation: 'EXPAND_RECURRENCE',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Greedy Overkill via Recurrence',
        diagnosisExplanation: 'Problems satisfying the matroid greedy-choice property do not require multi-branch recurrence trees; locally optimal choices yield global optimality.',
        enemyAdaptationName: 'Combinatorial Drag',
        enemyAdaptationEffect: 'The Colossus drags down greedy decisions.',
        repairConcept: 'Merge lowest two frequencies directly via priority queue.',
        echoVaultId: 'vault_dsa_optimization',
      },
      {
        triggerOperation: 'VERIFY_INVARIANT',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'Premature Matroid Invariant',
        diagnosisExplanation: 'Cannot verify prefix-free or MST invariant before detecting and eliminating cycles via Disjoint Set Union.',
        enemyAdaptationName: 'Cyclic Feedback',
        enemyAdaptationEffect: 'The Colossus discharges cyclic energy.',
        repairConcept: 'Use Find-Union to verify acyclic matroid independence.',
        echoVaultId: 'vault_dsa_optimization',
      },
    ],
    enemy: {
      name: 'The Matroid Sovereign',
      title: 'Master of Local Greed',
      hp: 265,
      attack: 33,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Greed without matroid structure is mere blind haste!',
    },
    rewardXp: 350,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 10 (Level 110): Dynamic Programming Matrix
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd10',
    levelNumber: 110,
    levelTitle: 'Trial 10: The Dynamic Programming Matrix',
    subject: 'data_structures_algorithms',
    topic: 'Optimal Substructure + Overlapping Subproblems + 2D Tabulation',
    conceptName: 'Dynamic Programming Matrix',
    pathType: 'hidden_trial',
    trialOrder: 10,
    compressedConcepts: ['dsa_dp_formulation', 'dsa_dp_tabulation'],
    fallbackMainPathLevelMap: {
      dsa_dp_formulation: 35,
      dsa_dp_tabulation: 37,
    },
    objective: 'Formulate Bellman state equations, eliminate exponential recursion via 2D memoized tabulation, and reconstruct optimal solutions.',
    problemStatement: 'Longest Common Subsequence between strings X[1..m] and Y[1..n]. Define state dp[i][j], fill bottom-up in row-major order, and backtrack arrows to reconstruct the exact string.',
    initialEquationOrState: 'X[1..m], Y[1..n] | Overlapping states: 2^(m+n) -> DP Table: O(m*n)',
    targetState: 'DP Matrix Tabulated & Optimal Solution Reconstructed [MATRIX RESOLVED]',
    correctAnswer: 'dp[i][j] = dp[i-1][j-1] + 1 if match else max(dp[i-1][j], dp[i][j-1])',
    optimalSequence: ['FORMULATE_STATE', 'TABULATE_BOTTOM_UP', 'ALIGN_SUBSEQUENCE', 'RECONSTRUCT_SOLUTION'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'FORMULATE_STATE',
        resultingState: 'Bellman equation defined: dp[i][j] represents LCS length of prefixes X[1..i] and Y[1..j].',
        explanation: 'Optimal substructure and state definition established.',
        damageValue: 55,
      },
      {
        stepIndex: 1,
        operationKey: 'TABULATE_BOTTOM_UP',
        resultingState: 'Bottom-up iteration: table populated in O(m*n) time, caching all overlapping subproblems.',
        explanation: 'Eliminated exponential repeated calls through iterative table evaluation.',
        damageValue: 60,
      },
      {
        stepIndex: 2,
        operationKey: 'ALIGN_SUBSEQUENCE',
        resultingState: 'Transition evaluation: diagonal match gives +1, mismatch compares upper and left predecessor cells.',
        explanation: 'Exact optimal alignment verified at table cell dp[m][n].',
        damageValue: 60,
      },
      {
        stepIndex: 3,
        operationKey: 'RECONSTRUCT_SOLUTION',
        resultingState: 'DP Matrix Tabulated & Optimal Solution Reconstructed [MATRIX RESOLVED]',
        explanation: 'Backtracked pointer trail from dp[m][n] to reconstruct the maximal common sequence.',
        damageValue: 55,
      },
    ],
    validCards: getValidCards(['FORMULATE_STATE', 'TABULATE_BOTTOM_UP', 'ALIGN_SUBSEQUENCE', 'RECONSTRUCT_SOLUTION', 'BACKTRACK_SEARCH']),
    misconceptions: [
      {
        triggerOperation: 'TABULATE_BOTTOM_UP',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Tabulating Undefined Subproblems',
        diagnosisExplanation: 'Cannot allocate DP table dimensions without formulating state parameters (i, j) and base cases.',
        enemyAdaptationName: 'Dimension Collapse',
        enemyAdaptationEffect: 'The Eidolon collapses dimension strides; next card costs +1 Energy.',
        repairConcept: 'Formulate state DP[i, j] and optimal substructure relation.',
        echoVaultId: 'vault_dsa_optimization',
      },
      {
        triggerOperation: 'BACKTRACK_SEARCH',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Unmemoized Exponential Search',
        diagnosisExplanation: 'Overlapping subproblems cause exponential blowup in naive backtracking; bottom-up tabulation is required for polynomial time.',
        enemyAdaptationName: 'Exponential Miasma',
        enemyAdaptationEffect: 'The Eidolon slows memory bandwidth.',
        repairConcept: 'Fill 2D table iteratively in topological DAG order.',
        echoVaultId: 'vault_dsa_optimization',
      },
      {
        triggerOperation: 'RECONSTRUCT_SOLUTION',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'Premature Path Reconstruction',
        diagnosisExplanation: 'Cannot backtrack to reconstruct optimal alignment before completing cell scoring and direction pointers.',
        enemyAdaptationName: 'Traceback Severance',
        enemyAdaptationEffect: 'The Eidolon severs unlinked traceback pointers.',
        repairConcept: 'Align subsequence cells by comparing diagonal vs insertion/deletion costs.',
        echoVaultId: 'vault_dsa_optimization',
      },
    ],
    enemy: {
      name: 'The Memoization Golem',
      title: 'Architect of Overlapping States',
      hp: 270,
      attack: 34,
      visualType: 'algorithmic_horror',
      flavorQuote: 'Forget your past computations, and you shall repeat them until exhaustion!',
    },
    rewardXp: 360,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 11 (Level 111): Shortest Path Meridian
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd11',
    levelNumber: 111,
    levelTitle: 'Trial 11: The Shortest Path Meridian',
    subject: 'data_structures_algorithms',
    topic: 'Edge Relaxation + Negative Weight Cycle Detection + Triangle Inequality',
    conceptName: 'Shortest Path Meridian',
    pathType: 'hidden_trial',
    trialOrder: 11,
    compressedConcepts: ['dsa_shortest_paths', 'dsa_network_flows'],
    fallbackMainPathLevelMap: {
      dsa_shortest_paths: 41,
      dsa_network_flows: 42,
    },
    objective: 'Synthesize Dijkstra min-priority relaxation with Bellman-Ford negative weight cycle detection and triangle inequality verification.',
    problemStatement: 'Directed weighted network with potential negative weights. Relax edges greedily via min-heap, verify V-1 passes, detect negative cycles, and prove triangle inequality dist[v] <= dist[u] + w(u,v).',
    initialEquationOrState: 'Network G=(V,E,w) | Min-priority heap active | Triangle Inequality: Pending',
    targetState: 'Triangle Inequality & Negative Cycle Invariants Verified [MERIDIAN REACHED]',
    correctAnswer: 'dist[v] <= dist[u] + w(u, v) for all edges',
    optimalSequence: ['EXTRACT_MIN_DIST', 'RELAX_EDGE', 'DETECT_NEGATIVE_CYCLE', 'VERIFY_TRIANGLE_INEQUALITY'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'EXTRACT_MIN_DIST',
        resultingState: 'Min-heap pop: vertex u with minimal tentative distance finalized in O(log V) time.',
        explanation: 'Greedy extraction guarantees permanent shortest path for non-negative subgraphs.',
        damageValue: 55,
      },
      {
        stepIndex: 1,
        operationKey: 'RELAX_EDGE',
        resultingState: 'Edge relaxation: dist[v] updated to dist[u] + w(u, v) whenever a strictly shorter path is discovered.',
        explanation: 'Path relaxation invariant monotonically decreases tentative distances toward optimum.',
        damageValue: 60,
      },
      {
        stepIndex: 2,
        operationKey: 'DETECT_NEGATIVE_CYCLE',
        resultingState: 'V-th pass check: no edge can be further relaxed, proving absence of negative weight cycles.',
        explanation: 'If an edge can still relax after V-1 passes, an infinite negative cycle exists.',
        damageValue: 65,
      },
      {
        stepIndex: 3,
        operationKey: 'VERIFY_TRIANGLE_INEQUALITY',
        resultingState: 'Triangle Inequality & Negative Cycle Invariants Verified [MERIDIAN REACHED]',
        explanation: 'Formally confirmed triangle inequality holds globally across all reachable geodesics.',
        damageValue: 55,
      },
    ],
    validCards: getValidCards(['EXTRACT_MIN_DIST', 'RELAX_EDGE', 'DETECT_NEGATIVE_CYCLE', 'VERIFY_TRIANGLE_INEQUALITY', 'TREE_TRAVERSE']),
    misconceptions: [
      {
        triggerOperation: 'RELAX_EDGE',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Relaxing Unextracted Vertex',
        diagnosisExplanation: 'Dijkstra requires extracting minimum distance node from priority queue before relaxing outward edges.',
        enemyAdaptationName: 'Premature Relaxation',
        enemyAdaptationEffect: 'The Leviathan corrupts distance estimates; next card costs +1 Energy.',
        repairConcept: 'Extract vertex u with minimal dist[u] first.',
        echoVaultId: 'vault_dsa_optimization',
      },
      {
        triggerOperation: 'TREE_TRAVERSE',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Tree Traversal in Cyclic Network',
        diagnosisExplanation: 'Shortest path relaxation on weighted directed graphs requires edge relaxation with Bellman-Ford/Dijkstra, not naive tree walking.',
        enemyAdaptationName: 'Negative Weight Trap',
        enemyAdaptationEffect: 'The Leviathan sinks into negative weight cycles.',
        repairConcept: 'Relax edge (u, v): if dist[v] > dist[u] + w(u,v), update dist[v].',
        echoVaultId: 'vault_dsa_optimization',
      },
      {
        triggerOperation: 'VERIFY_TRIANGLE_INEQUALITY',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'Premature Invariant in Cyclic Graph',
        diagnosisExplanation: 'Cannot verify triangle inequality before testing for negative-weight cycles on the |V|-th relaxation pass.',
        enemyAdaptationName: 'Oscillation Storm',
        enemyAdaptationEffect: 'The Leviathan triggers unbounded negative oscillations.',
        repairConcept: 'Check if dist[v] > dist[u] + w(u,v) after |V|-1 iterations to detect negative cycles.',
        echoVaultId: 'vault_dsa_optimization',
      },
    ],
    enemy: {
      name: 'The Geodesic Leviathan',
      title: 'Devourer of Distant Paths',
      hp: 280,
      attack: 35,
      visualType: 'algorithmic_horror',
      flavorQuote: 'A negative cycle is a black hole where all distance collapses to minus infinity!',
    },
    rewardXp: 370,
    rewardMastery: 35,
  },

  // -------------------------------------------------------------------------
  // TRIAL 12 (Level 112): Complexity Horizon Boss: The Algorithmic Ascension
  // -------------------------------------------------------------------------
  {
    id: 'dsa_hidden_hd12',
    levelNumber: 112,
    levelTitle: 'The Algorithmic Ascension',
    subject: 'data_structures_algorithms',
    topic: 'Grand Mastery Synthesis: NP-Completeness + Poly-Reductions + Approximation Bounds',
    conceptName: 'The Algorithmic Ascension',
    pathType: 'hidden_trial',
    isBoss: true,
    trialOrder: 12,
    compressedConcepts: ['dsa_np_reductions', 'dsa_approximation'],
    fallbackMainPathLevelMap: {
      dsa_np_reductions: 46,
      dsa_approximation: 52,
    },
    objective: 'Synthesize polynomial certificate verification, 3-SAT gadget reductions, and approximation ratio bounds against the Supreme Sovereign of the Hidden Path.',
    problemStatement: 'The ultimate computational synthesis: Verify an NP certificate in polynomial time, construct a gadget mapping 3-SAT to Vertex Cover, and prove a 2-approximation factor for Minimum Vertex Cover.',
    initialEquationOrState: 'The Algorithmic Ascension awaits | Verification + Reduction + Approximation',
    targetState: 'Supreme Computational Synthesis Complete: Invariance Ascended [SOVEREIGN DEFEATED]',
    correctAnswer: 'NP-Complete = in NP and NP-hard; Vertex Cover 2-approx via maximal matching',
    optimalSequence: ['VERIFY_CERTIFICATE', 'CONSTRUCT_REDUCTION', 'MAP_GADGET', 'BOUND_APPROXIMATION_RATIO', 'VERIFY_INVARIANT'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'VERIFY_CERTIFICATE',
        resultingState: 'Polynomial certificate check: candidate witness checked in deterministic O(n^c) time. Proven in NP.',
        explanation: 'Demonstrated polynomial-time verifiability, the defining hallmark of class NP.',
        damageValue: 60,
      },
      {
        stepIndex: 1,
        operationKey: 'CONSTRUCT_REDUCTION',
        resultingState: 'Reduction pipeline established: instance of 3-SAT converted into Vertex Cover instance in polynomial time.',
        explanation: 'Established many-one Karp reduction direction: A <=_p B.',
        damageValue: 65,
      },
      {
        stepIndex: 2,
        operationKey: 'MAP_GADGET',
        resultingState: 'Gadget constructed: literal variable gadgets and clause triangles correctly wired.',
        explanation: 'Proven equivalence: 3-SAT formula is satisfiable iff graph has vertex cover of size k = n + 2m.',
        damageValue: 70,
      },
      {
        stepIndex: 3,
        operationKey: 'BOUND_APPROXIMATION_RATIO',
        resultingState: 'Approximation analysis: maximal matching covers at most 2 * OPT vertices, guaranteeing rho = 2.',
        explanation: 'Proved 2-approximation bound when polynomial exact solution is intractable.',
        damageValue: 70,
      },
      {
        stepIndex: 4,
        operationKey: 'VERIFY_INVARIANT',
        resultingState: 'Supreme Computational Synthesis Complete: Invariance Ascended [SOVEREIGN DEFEATED]',
        explanation: 'Total synthesis achieved! The boundary between P, NP, and Intractability is fully mastered.',
        damageValue: 60,
      },
    ],
    validCards: getValidCards(['VERIFY_CERTIFICATE', 'CONSTRUCT_REDUCTION', 'MAP_GADGET', 'BOUND_APPROXIMATION_RATIO', 'VERIFY_INVARIANT', 'COUNT_OPERATIONS']),
    misconceptions: [
      {
        triggerOperation: 'CONSTRUCT_REDUCTION',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Reducing Without Certificate Verification',
        diagnosisExplanation: 'To establish NP-completeness, you must first verify that problem L is in NP by checking a polynomial-time verifier/certificate.',
        enemyAdaptationName: 'Non-Deterministic Fracture',
        enemyAdaptationEffect: 'The Ascension shatters unverified certificates; next card costs +1 Energy.',
        repairConcept: 'Verify polynomial-time certificate validation first.',
        echoVaultId: 'vault_dsa_complexity',
      },
      {
        triggerOperation: 'COUNT_OPERATIONS',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Naive Exact Counting on NP-Complete Instance',
        diagnosisExplanation: 'Attempting exact enumeration of an NP-complete problem causes 2^n exponential explosion; polynomial reduction to a known hard problem is required.',
        enemyAdaptationName: 'Exponential Singularity',
        enemyAdaptationEffect: 'The Ascension distorts space-time with 2^n drag.',
        repairConcept: 'Construct polynomial-time mapping reduction f(x) from 3-SAT / Vertex Cover.',
        echoVaultId: 'vault_dsa_complexity',
      },
      {
        triggerOperation: 'BOUND_APPROXIMATION_RATIO',
        atStepIndex: 2,
        diagnosisType: 'procedural_error',
        title: 'Bounding Ratio Before Gadget Mapping',
        diagnosisExplanation: 'Approximation guarantees cannot be computed before component-by-component gadget transformation is formalized.',
        enemyAdaptationName: 'Gadget Disruption',
        enemyAdaptationEffect: 'The Ascension disassembles unmapped gadgets.',
        repairConcept: 'Map variable and clause gadgets preserving truth assignment invariants.',
        echoVaultId: 'vault_dsa_complexity',
      },
      {
        triggerOperation: 'VERIFY_INVARIANT',
        atStepIndex: 3,
        diagnosisType: 'procedural_error',
        title: 'Premature Invariant Claim',
        diagnosisExplanation: 'Cannot certify polynomial approximation ratio without proving alpha-approximation bound alpha = ALG / OPT.',
        enemyAdaptationName: 'Inapproximability Ward',
        enemyAdaptationEffect: 'The Ascension repels unproven ratio assertions.',
        repairConcept: 'Bound cost ratio ALG(I) <= alpha * OPT(I) before final verification.',
        echoVaultId: 'vault_dsa_complexity',
      },
    ],
    enemy: {
      name: 'The Algorithmic Ascension',
      title: 'Supreme Sovereign of the Hidden Path',
      hp: 480,
      attack: 40,
      visualType: 'sovereign_archon',
      flavorQuote: 'Only those who comprehend the frontier of P versus NP may claim the crown of Ascension!',
    },
    rewardXp: 500,
    rewardMastery: 50,
  },
];
