import { Card } from '../types/game';
import { EncounterDefinition, EchoDungeonDefinition, SubjectInfo } from '../types/curriculum';

export const MATH_STARTER_CARDS: Card[] = [
  {
    id: 'math_factor',
    name: 'Factor',
    cost: 1,
    subject: 'mathematics',
    rarity: 'common',
    operationKey: 'FACTOR',
    description: 'Decompose an algebraic polynomial into binomial product factors.',
    effectText: 'Decomposes polynomial into binomial factors. Deals 30 DMG & shields 10.',
    damage: 30,
    shield: 10,
    iconName: 'Divide',
    flavorQuote: 'Order emerges from fractured polynomials.',
  },
  {
    id: 'math_solve',
    name: 'Solve',
    cost: 1,
    subject: 'mathematics',
    rarity: 'common',
    operationKey: 'SOLVE',
    description: 'Apply zero-product property or algebraic isolation to extract roots.',
    effectText: 'Applies Zero Product Property to extract roots. Deals 45 DMG & shields 15.',
    damage: 45,
    shield: 15,
    iconName: 'CheckCircle',
    flavorQuote: 'Truth reveals itself at zero.',
  },
  {
    id: 'math_verify',
    name: 'Verify',
    cost: 1,
    subject: 'mathematics',
    rarity: 'common',
    operationKey: 'VERIFY',
    description: 'Substitute roots back into the initial equation to guarantee proof.',
    effectText: 'Substitutes roots to validate axiom proof. Deals 25 DMG & shields 20.',
    damage: 25,
    shield: 20,
    iconName: 'ShieldCheck',
    flavorQuote: 'A hunter trusts only proven axioms.',
  },
  {
    id: 'math_expand',
    name: 'Expand',
    cost: 1,
    subject: 'mathematics',
    rarity: 'common',
    operationKey: 'EXPAND',
    description: 'Multiply grouped factors into standard polynomial form.',
    effectText: 'Expands grouped factors. Deals 5 recoil DMG if already in standard form.',
    damage: 0,
    shield: 0,
    iconName: 'Maximize2',
    flavorQuote: 'Expanding what is already expanded invites chaos.',
  },
  {
    id: 'math_substitute',
    name: 'Substitute',
    cost: 1,
    subject: 'mathematics',
    rarity: 'common',
    operationKey: 'SUBSTITUTE',
    description: 'Replace variable instances with equivalent expressions or numbers.',
    effectText: 'Substitutes variable. Shields 15.',
    damage: 10,
    shield: 15,
    iconName: 'RefreshCw',
    flavorQuote: 'Equivalence is the hunter\'s mirror.',
  },
  {
    id: 'math_simplify',
    name: 'Simplify',
    cost: 1,
    subject: 'mathematics',
    rarity: 'common',
    operationKey: 'SIMPLIFY',
    description: 'Combine like terms and reduce constants to minimal representation.',
    effectText: 'Reduces terms. Deals 15 DMG & draws 1 card.',
    damage: 15,
    shield: 5,
    drawCards: 1,
    iconName: 'Sparkles',
    flavorQuote: 'Clarity strikes harder than complexity.',
  },
];

export const MATH_ENCOUNTERS: EncounterDefinition[] = [
  {
    id: 'math_lvl_1',
    levelNumber: 1,
    levelTitle: 'The Fractured Equation',
    subject: 'mathematics',
    topic: 'Quadratic Factorization',
    conceptName: 'Zero Product Property & Factoring',
    pathType: 'main',
    objective: 'Decompose the quadratic equation and determine its valid roots.',
    problemStatement: 'Deconstruct and neutralize the equation: x² + 5x + 6 = 0',
    initialEquationOrState: 'x² + 5x + 6 = 0',
    targetState: 'x = -2, -3 [VERIFIED]',
    optimalSequence: ['FACTOR', 'SOLVE', 'VERIFY'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'FACTOR',
        resultingState: '(x + 2)(x + 3) = 0',
        explanation: 'Identified binomial factors (x + 2) and (x + 3) whose product is 6 and sum is 5.',
        damageValue: 35,
      },
      {
        stepIndex: 1,
        operationKey: 'SOLVE',
        resultingState: 'x = -2, x = -3',
        explanation: 'Applied Zero Product Property: (x + 2)=0 or (x + 3)=0.',
        damageValue: 45,
      },
      {
        stepIndex: 2,
        operationKey: 'VERIFY',
        resultingState: '0 = 0 [ABSOLUTE PROOF]',
        explanation: 'Substituted roots into original polynomial. Exact equality confirmed!',
        damageValue: 30,
      },
    ],
    validCards: MATH_STARTER_CARDS,
    misconceptions: [
      {
        triggerOperation: 'EXPAND',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Premature Expansion Error',
        diagnosisExplanation:
          'The equation x² + 5x + 6 = 0 is already in expanded standard form. Attempting to expand does not simplify the equation—it creates cyclical confusion before finding roots.',
        enemyAdaptationName: 'Factor Trap',
        enemyAdaptationEffect: 'The Quadratic Beast hardens its crystalline shell. Non-factoring actions cost +1 Energy!',
        repairConcept: 'Recognizing Standard Form vs. Factored Form',
        echoVaultId: 'vault_factorization',
      },
      {
        triggerOperation: 'SUBSTITUTE',
        atStepIndex: 0,
        diagnosisType: 'impulsive_guessing',
        title: 'Brute-Force Guessing Without Structural Decomposition',
        diagnosisExplanation:
          'Attempted substitution before factoring or isolating variables. While trial-and-error can test single numbers, it fails to systematically resolve algebraic roots.',
        enemyAdaptationName: 'Deliberation Curse',
        enemyAdaptationEffect: 'The Quadratic Beast silences instinct. Next turn requires deliberate operation sequencing.',
        repairConcept: 'Systematic Factorization',
        echoVaultId: 'vault_factorization',
      },
    ],
    enemy: {
      name: 'Quadratic Beast',
      title: 'Titan of Fractured Polynomials',
      hp: 100,
      attack: 18,
      visualType: 'quadratic_beast',
      flavorQuote: 'I am the product of broken roots. Factor me or crumble!',
    },
    rewardXp: 120,
    rewardMastery: 25,
    unlockedCard: {
      id: 'math_factor_mastery',
      name: 'Factor Mastery',
      cost: 1,
      subject: 'mathematics',
      rarity: 'rare',
      operationKey: 'FACTOR',
      description: 'Instantly split complex quadratics with high precision.',
      effectText: 'Deals 45 DMG & gains 20 Shield. Pierces defensive shields.',
      damage: 45,
      shield: 20,
      iconName: 'Flame',
      flavorQuote: 'Roots cannot hide from a master.',
    },
  },
  {
    id: 'math_lvl_2',
    levelNumber: 2,
    levelTitle: 'The Simultaneous Ward',
    subject: 'mathematics',
    topic: 'Linear Systems',
    conceptName: 'Substitution & Elimination',
    pathType: 'main',
    objective: 'Solve the system of linear equations to isolate variable values.',
    problemStatement: 'Neutralize the dual wards: 2x + y = 7 and x - y = 2',
    initialEquationOrState: '{ 2x + y = 7, x - y = 2 }',
    targetState: 'x = 3, y = 1 [VERIFIED]',
    optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'SIMPLIFY',
        resultingState: '3x = 9 => x = 3',
        explanation: 'Added both equations directly to eliminate the y variable.',
        damageValue: 40,
      },
      {
        stepIndex: 1,
        operationKey: 'SOLVE',
        resultingState: '3 - y = 2 => y = 1',
        explanation: 'Substituted x = 3 back to solve for y = 1.',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'VERIFY',
        resultingState: '2(3) + 1 = 7 [TRUE]',
        explanation: 'Both conditions satisfied simultaneously.',
        damageValue: 30,
      },
    ],
    validCards: MATH_STARTER_CARDS,
    misconceptions: [
      {
        triggerOperation: 'EXPAND',
        atStepIndex: 0,
        diagnosisType: 'algorithmic_inefficiency',
        title: 'Inefficient System Resolution',
        diagnosisExplanation: 'Expanding linear systems adds redundant terms when direct elimination is available.',
        enemyAdaptationName: 'Efficiency Barrier',
        enemyAdaptationEffect: 'Increases enemy shield by 25.',
        repairConcept: 'Linear Elimination',
        echoVaultId: 'vault_factorization',
      },
    ],
    enemy: {
      name: 'Equation Warden',
      title: 'Guardian of Intersecting Lines',
      hp: 120,
      attack: 22,
      visualType: 'quadratic_beast',
      flavorQuote: 'Two paths cross—fail to resolve them and be severed!',
    },
    rewardXp: 180,
    rewardMastery: 30,
  },
  {
    id: 'math_lvl_3',
    levelNumber: 3,
    levelTitle: 'The Radical Boundary',
    subject: 'mathematics',
    topic: 'Radical Roots & Discriminant',
    conceptName: 'Discriminant & Radical Root Extraction',
    pathType: 'main',
    objective: 'Isolate radical expressions and compute the exact roots.',
    problemStatement: 'Isolate radicals and determine exact roots of: x² - 4x + 1 = 0',
    initialEquationOrState: 'x² - 4x + 1 = 0',
    targetState: 'x = 2 ± √3 [VERIFIED]',
    optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'SIMPLIFY',
        resultingState: '(x - 2)² - 3 = 0 => (x - 2)² = 3',
        explanation: 'Completed the square to isolate the radical component.',
        damageValue: 40,
      },
      {
        stepIndex: 1,
        operationKey: 'SOLVE',
        resultingState: 'x - 2 = ±√3 => x = 2 ± √3',
        explanation: 'Extracted both radical roots using the quadratic discriminant.',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'VERIFY',
        resultingState: '(2+√3)² - 4(2+√3) + 1 = 0 [AXIOM SOUND]',
        explanation: 'Radical conjugate confirmed through backward substitution.',
        damageValue: 35,
      },
    ],
    validCards: MATH_STARTER_CARDS,
    misconceptions: [],
    enemy: {
      name: 'Radical Golem',
      title: 'Sentinel of Irrationals',
      hp: 130,
      attack: 24,
      visualType: 'quadratic_beast',
      flavorQuote: 'Under the radical sign, integer certainties dissolve into dust.',
    },
    rewardXp: 220,
    rewardMastery: 35,
  },
  {
    id: 'math_lvl_4',
    levelNumber: 4,
    levelTitle: 'The Axiom Verification',
    subject: 'mathematics',
    topic: 'Domain Constraints & Proof',
    conceptName: 'Verification & Extraneous Solution Rejection',
    pathType: 'main',
    objective: 'Evaluate candidate solutions and reject extraneous roots.',
    problemStatement: 'Verify root validity and reject extraneous solutions: √(2x + 3) = x',
    initialEquationOrState: '√(2x + 3) = x (Constraint: x ≥ 0)',
    targetState: 'x = 3 [VALID], x = -1 [EXTRANEOUS REJECTED]',
    optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'SIMPLIFY',
        resultingState: '2x + 3 = x² => x² - 2x - 3 = 0',
        explanation: 'Squared both sides to eliminate radical expression.',
        damageValue: 45,
      },
      {
        stepIndex: 1,
        operationKey: 'SOLVE',
        resultingState: '(x - 3)(x + 1) = 0 => Candidate roots: x = 3, x = -1',
        explanation: 'Factored algebraic polynomial into two candidate roots.',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'VERIFY',
        resultingState: '√(2(3)+3) = 3 [TRUE] | √(2(-1)+3) ≠ -1 [EXTRANEOUS REJECTED]',
        explanation: 'Rigorous backward check rejected invalid root x = -1.',
        damageValue: 40,
      },
    ],
    validCards: MATH_STARTER_CARDS,
    misconceptions: [],
    enemy: {
      name: 'Axiom Sentinel',
      title: 'Purifier of Extraneous Shadows',
      hp: 140,
      attack: 25,
      visualType: 'quadratic_beast',
      flavorQuote: 'False roots masquerade as truth. Only backward proof reveals the impostor!',
    },
    rewardXp: 260,
    rewardMastery: 40,
  },
  {
    id: 'math_boss',
    levelNumber: 5,
    levelTitle: 'The Singularity Archon',
    subject: 'mathematics',
    topic: 'Synthesis & Complex Factoring',
    conceptName: 'The Mathematical Guardian Boss',
    isBoss: true,
    pathType: 'main',
    objective: 'Deconstruct the quadratic singularity and prove both root values.',
    problemStatement: 'Transcend the core: 2x² + 7x + 3 = 0',
    initialEquationOrState: '2x² + 7x + 3 = 0',
    targetState: 'x = -1/2, -3 [BOSS MASTERY]',
    optimalSequence: ['FACTOR', 'SOLVE', 'VERIFY'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'FACTOR',
        resultingState: '(2x + 1)(x + 3) = 0',
        explanation: 'Split the middle term: 2x² + 6x + x + 3 = 0 => (2x + 1)(x + 3) = 0.',
        damageValue: 60,
      },
      {
        stepIndex: 1,
        operationKey: 'SOLVE',
        resultingState: 'x = -1/2, x = -3',
        explanation: 'Solved roots from non-monic quadratic.',
        damageValue: 70,
      },
      {
        stepIndex: 2,
        operationKey: 'VERIFY',
        resultingState: 'SINGULARITY RESTORED [TOTAL VICTORY]',
        explanation: 'The fractured realm achieves mathematical harmony.',
        damageValue: 50,
      },
    ],
    validCards: MATH_STARTER_CARDS,
    misconceptions: [],
    enemy: {
      name: 'The Mathematical Guardian',
      title: 'Archon of the Fractured Realm',
      hp: 180,
      attack: 26,
      visualType: 'mathematical_guardian',
      flavorQuote: 'Axioms shatter, yet truths endure. Prove your understanding before the Spire!',
    },
    rewardXp: 350,
    rewardMastery: 45,
  },
  // HIDDEN DIFFICULT PATH: THE CRUCIBLE OF COMPRESSION
  {
    id: 'math_hidden_trial_1',
    levelNumber: 101,
    levelTitle: 'Trial 1: The Dual Crucible',
    subject: 'mathematics',
    topic: 'Factoring + Linear Systems',
    conceptName: 'The Dual Crucible',
    pathType: 'hidden_trial',
    trialOrder: 1,
    compressedConcepts: ['math_factorization', 'math_linear_systems'],
    fallbackMainPathLevelMap: {
      math_linear_systems: 2,
      math_factorization: 1,
    },
    objective: 'Combine substitution and factoring to resolve the coupled system.',
    problemStatement: 'Resolve the coupled anomaly: y = x + 1 and x² + yx - 6 = 0',
    initialEquationOrState: '{ y = x + 1, x² + yx - 6 = 0 }',
    targetState: 'x = 3/2 (y = 5/2) OR x = -2 (y = -1) [CRUCIBLE MASTERED]',
    optimalSequence: ['SUBSTITUTE', 'FACTOR', 'SOLVE'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'SUBSTITUTE',
        resultingState: 'x² + (x + 1)x - 6 = 0 => 2x² + x - 6 = 0',
        explanation: 'Substituted y = x + 1 to reduce system to a single-variable quadratic.',
        damageValue: 45,
      },
      {
        stepIndex: 1,
        operationKey: 'FACTOR',
        resultingState: '(2x - 3)(x + 2) = 0',
        explanation: 'Decomposed 2x² + x - 6 into binomial factors (2x - 3)(x + 2).',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'SOLVE',
        resultingState: 'x = 3/2 (y = 5/2) and x = -2 (y = -1)',
        explanation: 'Extracted both root pairs satisfying the simultaneous system.',
        damageValue: 55,
      },
    ],
    validCards: MATH_STARTER_CARDS,
    misconceptions: [
      {
        triggerOperation: 'FACTOR',
        atStepIndex: 0,
        diagnosisType: 'prerequisite_gap',
        title: 'Coupled Factorization Attempt',
        diagnosisExplanation: 'Cannot factor an equation containing multiple coupled variables before eliminating one.',
        enemyAdaptationName: 'Coupled Singularity Shield',
        enemyAdaptationEffect: 'Gains 30 shield and increases action energy cost.',
        repairConcept: 'Linear Substitution',
        echoVaultId: 'vault_factorization',
      },
      {
        triggerOperation: 'EXPAND',
        atStepIndex: 1,
        diagnosisType: 'procedural_error',
        title: 'Redundant Expansion in Quadratic State',
        diagnosisExplanation: 'Attempted expansion when binomial factorization was required.',
        enemyAdaptationName: 'Entropy Backlash',
        enemyAdaptationEffect: 'Deals 15 damage to player.',
        repairConcept: 'Quadratic Factoring',
        echoVaultId: 'vault_factorization',
      },
    ],
    enemy: {
      name: 'Dual Singularity Chimera',
      title: 'Monstrosity of Entangled Axioms',
      hp: 140,
      attack: 24,
      visualType: 'quadratic_beast',
      flavorQuote: 'Two systems intertwine. Fail to isolate them and dissolve into paradox!',
    },
    rewardXp: 240,
    rewardMastery: 35,
  },
  {
    id: 'math_hidden_trial_2',
    levelNumber: 102,
    levelTitle: 'Trial 2: The Abyssal Proof',
    subject: 'mathematics',
    topic: 'Radical Roots + Verification',
    conceptName: 'The Abyssal Proof',
    pathType: 'hidden_trial',
    trialOrder: 2,
    compressedConcepts: ['math_roots_radicals', 'math_verification'],
    unlocksBossDirectly: true,
    fallbackMainPathLevelMap: {
      math_roots_radicals: 3,
      math_verification: 4,
    },
    prestigeRewards: {
      title: 'Axiom Compressor',
      relic: 'Singularity Prism',
      bonusXp: 300,
    },
    objective: 'Square both sides to solve the quadratic and strictly eliminate extraneous roots.',
    problemStatement: 'Neutralize radical singularity and reject extraneous phantoms: √(x² - 5) = x - 1',
    initialEquationOrState: '√(x² - 5) = x - 1 (Constraint: x ≥ 1)',
    targetState: 'x = 3 [ABSOLUTE PROOF]',
    optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
    stepTransformations: [
      {
        stepIndex: 0,
        operationKey: 'SIMPLIFY',
        resultingState: 'x² - 5 = x² - 2x + 1 => 2x = 6',
        explanation: 'Squared both radical sides; quadratic term canceled out!',
        damageValue: 45,
      },
      {
        stepIndex: 1,
        operationKey: 'SOLVE',
        resultingState: '2x = 6 => x = 3',
        explanation: 'Isolated candidate root under radical constraints.',
        damageValue: 50,
      },
      {
        stepIndex: 2,
        operationKey: 'VERIFY',
        resultingState: '√(3² - 5) = 2 = 3 - 1 [ABSOLUTE PROOF]',
        explanation: 'Substituted root back into original equation. Verified strictly!',
        damageValue: 60,
      },
    ],
    validCards: MATH_STARTER_CARDS,
    misconceptions: [
      {
        triggerOperation: 'EXPAND',
        atStepIndex: 0,
        diagnosisType: 'procedural_error',
        title: 'Radical Order Violation',
        diagnosisExplanation: 'Cannot expand non-polynomial radical expressions without clearing radicals first.',
        enemyAdaptationName: 'Radical Reflection',
        enemyAdaptationEffect: 'Gains 30 shield.',
        repairConcept: 'Radical Simplification',
        echoVaultId: 'vault_factorization',
      },
    ],
    enemy: {
      name: 'Abyssal Invariant Dragon',
      title: 'Overseer of Compression',
      hp: 155,
      attack: 26,
      visualType: 'mathematical_guardian',
      flavorQuote: 'Axioms compress under my gaze. Prove your roots or be crushed by the Spire!',
    },
    rewardXp: 300,
    rewardMastery: 40,
  },
];

export const MATH_ECHO_VAULT: EchoDungeonDefinition = {
  id: 'vault_factorization',
  subject: 'mathematics',
  title: 'The Factor Vault',
  weaknessLabel: 'Procedural Factoring Ordering',
  misconceptionType: 'Premature Expansion / Misconception of Standard Form',
  problemContext: 'Encountered: x² + 5x + 6 = 0',
  breakdownExplanation:
    'When faced with an equation in standard form ax² + bx + c = 0, expanding it further increases complexity. Factoring decomposes the quadratic into binomial factors whose product is c and sum is b, enabling root isolation via the Zero Product Property.',
  coreRule: 'Rule: If an expression is in standard form ax² + bx + c, your first operation must be FACTOR, never EXPAND.',
  steps: [
    {
      stepNumber: 1,
      instruction: 'Identify the correct factor pair for x² + 5x + 6 = 0:',
      options: [
        {
          label: '(x + 1)(x + 6)',
          operationKey: 'FACTOR_WRONG',
          isCorrect: false,
          feedback: 'Incorrect: 1 + 6 = 7, but the middle term coefficient is 5.',
        },
        {
          label: '(x + 2)(x + 3)',
          operationKey: 'FACTOR',
          isCorrect: true,
          feedback: 'Correct! 2 * 3 = 6 and 2 + 3 = 5. The equation decomposes into binomial factors.',
        },
        {
          label: 'Expand again',
          operationKey: 'EXPAND',
          isCorrect: false,
          feedback: 'Avoid repeating the mistake! Expanding creates unnecessary complexity.',
        },
      ],
    },
    {
      stepNumber: 2,
      instruction: 'Now apply the Zero Product Property to (x + 2)(x + 3) = 0:',
      options: [
        {
          label: 'Multiply back to standard form',
          operationKey: 'EXPAND',
          isCorrect: false,
          feedback: 'Multiplying back undoes your factoring step.',
        },
        {
          label: 'Set each factor to zero: x = -2 or x = -3',
          operationKey: 'SOLVE',
          isCorrect: true,
          feedback: 'Flawless! If A * B = 0, then A = 0 or B = 0.',
        },
        {
          label: 'Set sum of factors to zero: (x + 2) + (x + 3) = 0',
          operationKey: 'SOLVE_WRONG',
          isCorrect: false,
          feedback: 'Incorrect: The Zero Product Property applies to multiplication factors, not additions.',
        },
      ],
    },
  ],
  rewardMastery: 20,
};

export const MATHEMATICS_SUBJECT_INFO: SubjectInfo = {
  id: 'mathematics',
  name: 'Mathematics',
  realmName: 'The Fractured Realm',
  realmDescription: 'A crystalline dimension where unproven conjectures and shattered equations take monstrous physical form.',
  themeColor: '#06b6d4',
  accentColor: '#38bdf8',
  secondaryColor: '#0284c7',
  iconName: 'Binary',
  storyIntro: {
    title: 'The Fractured Realm Awakens',
    narration: [
      'Numbers once governed this cosmic spire in absolute geometric harmony.',
      'Then the primordial axioms fractured. Unsolved polynomials coalesced into ravenous beasts.',
      'As a Knowledge Hunter, your cognitive cards are not weapons of steel, but instruments of mathematical truth.',
    ],
    conceptCardIntro: [
      {
        cardName: 'FACTOR',
        quote: 'Decompose chaos into solvable binomial components.',
        role: 'Breakdown & Structure',
      },
      {
        cardName: 'SOLVE',
        quote: 'Harness the Zero Product Property to extract underlying roots.',
        role: 'Resolution & Strike',
      },
      {
        cardName: 'VERIFY',
        quote: 'Anchor your conclusion in rigorous axiom validation.',
        role: 'Shield & Proof',
      },
    ],
  },
  levels: [
    {
      id: 'math_lvl_1',
      levelNumber: 1,
      title: 'The Fractured Equation',
      topic: 'Quadratic Factorization',
      isBoss: false,
      pathType: 'main',
    },
    {
      id: 'math_lvl_2',
      levelNumber: 2,
      title: 'The Simultaneous Ward',
      topic: 'Linear Systems',
      isBoss: false,
      pathType: 'main',
      requiredCompletedLevel: 1,
    },
    {
      id: 'math_lvl_3',
      levelNumber: 3,
      title: 'The Radical Boundary',
      topic: 'Radical Roots & Discriminant',
      isBoss: false,
      pathType: 'main',
      requiredCompletedLevel: 2,
    },
    {
      id: 'math_lvl_4',
      levelNumber: 4,
      title: 'The Axiom Verification',
      topic: 'Verification & Extraneous Roots',
      isBoss: false,
      pathType: 'main',
      requiredCompletedLevel: 3,
    },
    {
      id: 'math_boss',
      levelNumber: 5,
      title: 'The Singularity Archon',
      topic: 'Archon Axiom Synthesis',
      isBoss: true,
      pathType: 'main',
      requiredCompletedLevel: 4,
    },
    // The Crucible of Compression (Hidden Path)
    {
      id: 'math_hidden_trial_1',
      levelNumber: 101,
      title: 'The Dual Crucible',
      topic: 'Factoring + Systems',
      isBoss: false,
      pathType: 'hidden_trial',
      trialOrder: 1,
      compressedConcepts: ['math_factorization', 'math_linear_systems'],
      requiredCompletedLevel: 1,
    },
    {
      id: 'math_hidden_trial_2',
      levelNumber: 102,
      title: 'The Abyssal Proof',
      topic: 'Roots + Verification',
      isBoss: false,
      pathType: 'hidden_trial',
      trialOrder: 2,
      compressedConcepts: ['math_roots_radicals', 'math_verification'],
      requiredCompletedLevel: 101,
    },
  ],
};
