import { SubjectId } from '../types/game';
import { StepTransformation, MisconceptionRule, SolutionPathDefinition, RecoveryPathDefinition } from '../types/curriculum';

export interface QuestionVariant {
  id: string;
  conceptKey: string;
  subject: SubjectId;
  levelNumber: number;
  difficulty: number;
  objective: string;
  problemStatement: string;
  initialEquationOrState: string;
  targetState: string;
  correctAnswer?: string;
  optimalSequence: string[];
  stepTransformations: StepTransformation[];
  misconceptions: MisconceptionRule[];
  alternativePaths?: SolutionPathDefinition[];
  recoveryPaths?: RecoveryPathDefinition[];
}

export const QUESTION_POOLS: Record<string, QuestionVariant[]> = {
  // -------------------------------------------------------------
  // MATHEMATICS LEVEL 1: Quadratic Factorization
  // -------------------------------------------------------------
  'mathematics_1': [
    {
      id: 'math_l1_q1',
      conceptKey: 'math_factorization',
      subject: 'mathematics',
      levelNumber: 1,
      difficulty: 1,
      objective: 'Decompose the quadratic equation and determine its valid roots.',
      problemStatement: 'Deconstruct and neutralize the equation: x² + 5x + 6 = 0',
      initialEquationOrState: 'x² + 5x + 6 = 0',
      targetState: 'x = -2, -3 [VERIFIED]',
      optimalSequence: ['FACTOR', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'FACTOR',
          resultingState: '(x + 2)(x + 3) = 0',
          explanation: 'Identified binomial factors (x + 2) and (x + 3) whose product is 6 and sum is 5.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: 'x = -2, x = -3',
          explanation: 'Applied Zero Product Property: (x + 2)=0 or (x + 3)=0.',
          damageValue: 45,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '0 = 0 [ABSOLUTE PROOF]',
          explanation: 'Substituted roots into original polynomial. Exact equality confirmed!',
          damageValue: 30,
        },
      ],
      misconceptions: [
        {
          triggerOperation: 'EXPAND',
          atStepIndex: 0,
          diagnosisType: 'procedural_error',
          title: 'Premature Expansion Error',
          diagnosisExplanation: 'The equation is already in expanded form. Factoring is needed.',
          enemyAdaptationName: 'Factor Trap',
          enemyAdaptationEffect: 'The Quadratic Beast hardens its shell. Non-factoring actions cost +1 Energy!',
          repairConcept: 'Recognizing Standard Form vs. Factored Form',
          echoVaultId: 'vault_factorization',
        },
      ],
    },
    {
      id: 'math_l1_q2',
      conceptKey: 'math_factorization',
      subject: 'mathematics',
      levelNumber: 1,
      difficulty: 1,
      objective: 'Decompose the quadratic equation and determine its valid roots.',
      problemStatement: 'Deconstruct and neutralize the equation: x² + 7x + 12 = 0',
      initialEquationOrState: 'x² + 7x + 12 = 0',
      targetState: 'x = -3, -4 [VERIFIED]',
      optimalSequence: ['FACTOR', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'FACTOR',
          resultingState: '(x + 3)(x + 4) = 0',
          explanation: 'Identified binomial factors (x + 3) and (x + 4) whose product is 12 and sum is 7.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: 'x = -3, x = -4',
          explanation: 'Applied Zero Product Property: x = -3 or x = -4.',
          damageValue: 45,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '0 = 0 [ABSOLUTE PROOF]',
          explanation: 'Verified: (-3)² + 7(-3) + 12 = 0.',
          damageValue: 30,
        },
      ],
      misconceptions: [
        {
          triggerOperation: 'EXPAND',
          atStepIndex: 0,
          diagnosisType: 'procedural_error',
          title: 'Premature Expansion Error',
          diagnosisExplanation: 'The equation is already in expanded form. Factoring is needed.',
          enemyAdaptationName: 'Factor Trap',
          enemyAdaptationEffect: 'The enemy gains 20 Shield from premature expansion.',
          repairConcept: 'Recognizing Standard Form vs. Factored Form',
          echoVaultId: 'vault_factorization',
        },
      ],
    },
    {
      id: 'math_l1_q3',
      conceptKey: 'math_factorization',
      subject: 'mathematics',
      levelNumber: 1,
      difficulty: 1,
      objective: 'Decompose the quadratic equation and determine its valid roots.',
      problemStatement: 'Deconstruct and neutralize the equation: x² - 5x + 6 = 0',
      initialEquationOrState: 'x² - 5x + 6 = 0',
      targetState: 'x = 2, 3 [VERIFIED]',
      optimalSequence: ['FACTOR', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'FACTOR',
          resultingState: '(x - 2)(x - 3) = 0',
          explanation: 'Binomial factors: product is +6 and sum is -5.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: 'x = 2, x = 3',
          explanation: 'Applied Zero Product Property: x = 2 or x = 3.',
          damageValue: 45,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '0 = 0 [ABSOLUTE PROOF]',
          explanation: 'Verified: 2² - 5(2) + 6 = 0.',
          damageValue: 30,
        },
      ],
      misconceptions: [],
    },
    {
      id: 'math_l1_q4',
      conceptKey: 'math_factorization',
      subject: 'mathematics',
      levelNumber: 1,
      difficulty: 1,
      objective: 'Decompose the quadratic equation and determine its valid roots.',
      problemStatement: 'Deconstruct and neutralize the equation: x² + 8x + 15 = 0',
      initialEquationOrState: 'x² + 8x + 15 = 0',
      targetState: 'x = -3, -5 [VERIFIED]',
      optimalSequence: ['FACTOR', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'FACTOR',
          resultingState: '(x + 3)(x + 5) = 0',
          explanation: 'Binomial factors: product is 15 and sum is 8.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: 'x = -3, x = -5',
          explanation: 'Roots extracted: x = -3, x = -5.',
          damageValue: 45,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '0 = 0 [ABSOLUTE PROOF]',
          explanation: 'Substituted roots. Invariant holds.',
          damageValue: 30,
        },
      ],
      misconceptions: [],
    },
  ],

  // -------------------------------------------------------------
  // MATHEMATICS LEVEL 2: Linear Systems (Substitution & Elimination)
  // -------------------------------------------------------------
  'mathematics_2': [
    {
      id: 'math_l2_q1',
      conceptKey: 'math_linear_systems',
      subject: 'mathematics',
      levelNumber: 2,
      difficulty: 2,
      objective: 'Solve the system of linear equations to isolate variable values.',
      problemStatement: 'Neutralize the dual wards: 2x + y = 7 and x - y = 2',
      initialEquationOrState: '{ 2x + y = 7, x - y = 2 }',
      targetState: 'x = 3, y = 1 [VERIFIED]',
      correctAnswer: 'x = 3, y = 1',
      optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SIMPLIFY',
          resultingState: '3x = 9 => x = 3',
          explanation: 'Added both equations directly to eliminate the y variable.',
          damageValue: 40,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: '3 - y = 2 => y = 1',
          explanation: 'Substituted x = 3 back to solve for y = 1.',
          damageValue: 50,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '2(3) + 1 = 7 [TRUE]',
          explanation: 'Both conditions satisfied simultaneously.',
          damageValue: 30,
        },
      ],
      alternativePaths: [
        {
          id: 'path_substitution',
          name: 'Method B: Substitution',
          operations: ['SUBSTITUTE', 'SOLVE', 'VERIFY'],
          educationalMethod: 'Algebraic Substitution',
          difficulty: 2,
          completionCondition: 'x = 3, y = 1 [VERIFIED]',
          transformations: [
            {
              stepIndex: 0,
              operationKey: 'SUBSTITUTE',
              resultingState: 'x - (7 - 2x) = 2 => 3x - 7 = 2 => 3x = 9',
              explanation: 'Isolated y = 7 - 2x from eq 1 and substituted into eq 2.',
              damageValue: 40,
            },
            {
              stepIndex: 1,
              operationKey: 'SOLVE',
              resultingState: '3x = 9 => x = 3, y = 7 - 2(3) = 1',
              explanation: 'Solved linear equation for x and computed y.',
              damageValue: 50,
            },
            {
              stepIndex: 2,
              operationKey: 'VERIFY',
              resultingState: '2(3) + 1 = 7 and 3 - 1 = 2 [TRUE]',
              explanation: 'Both equations verified under substitution.',
              damageValue: 30,
            },
          ],
        },
      ],
      recoveryPaths: [
        {
          failedStepIndex: 0,
          triggerOperation: 'EXPAND',
          recoveryOperation: 'SIMPLIFY',
          resultingState: '3x = 9 => x = 3',
          remainingSequence: ['SOLVE', 'VERIFY'],
          explanation: 'Recovered from premature expansion. Eliminated y via addition.',
        },
      ],
      misconceptions: [
        {
          triggerOperation: 'EXPAND',
          atStepIndex: 0,
          diagnosisType: 'algorithmic_inefficiency',
          title: 'Inefficient System Resolution',
          diagnosisExplanation: 'Expanding linear systems adds redundant terms when direct elimination is available.',
          enemyAdaptationName: 'Efficiency Barrier',
          enemyAdaptationEffect: 'Increases enemy shield by 25.',
          repairConcept: 'Linear Elimination',
          echoVaultId: 'vault_factorization',
        },
      ],
    },
    {
      id: 'math_l2_q2',
      conceptKey: 'math_linear_systems',
      subject: 'mathematics',
      levelNumber: 2,
      difficulty: 2,
      objective: 'Solve the system of linear equations to isolate variable values.',
      problemStatement: 'Neutralize the dual wards: 3x + y = 11 and 2x - y = 4',
      initialEquationOrState: '{ 3x + y = 11, 2x - y = 4 }',
      targetState: 'x = 3, y = 2 [VERIFIED]',
      optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SIMPLIFY',
          resultingState: '5x = 15 => x = 3',
          explanation: 'Summed equations eliminating y: 5x = 15 yields x = 3.',
          damageValue: 40,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: '3(3) + y = 11 => y = 2',
          explanation: 'Substituted x = 3: y = 11 - 9 = 2.',
          damageValue: 50,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '2(3) - 2 = 4 [TRUE]',
          explanation: 'Verification confirms both equations hold.',
          damageValue: 30,
        },
      ],
      misconceptions: [],
    },
    {
      id: 'math_l2_q3',
      conceptKey: 'math_linear_systems',
      subject: 'mathematics',
      levelNumber: 2,
      difficulty: 2,
      objective: 'Solve the system of linear equations to isolate variable values.',
      problemStatement: 'Neutralize the dual wards: x + 2y = 8 and 3x - 2y = 4',
      initialEquationOrState: '{ x + 2y = 8, 3x - 2y = 4 }',
      targetState: 'x = 3, y = 2.5 [VERIFIED]',
      optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SIMPLIFY',
          resultingState: '4x = 12 => x = 3',
          explanation: 'Eliminated 2y by addition: 4x = 12 implies x = 3.',
          damageValue: 40,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: '3 + 2y = 8 => y = 2.5',
          explanation: 'Isolated y: 2y = 5 implies y = 2.5.',
          damageValue: 50,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '3(3) - 2(2.5) = 4 [TRUE]',
          explanation: 'Verified 9 - 5 = 4.',
          damageValue: 30,
        },
      ],
      misconceptions: [],
    },
    {
      id: 'math_l2_q4',
      conceptKey: 'math_linear_systems',
      subject: 'mathematics',
      levelNumber: 2,
      difficulty: 2,
      objective: 'Solve the system of linear equations to isolate variable values.',
      problemStatement: 'Neutralize the dual wards: 4x + 3y = 18 and x - 3y = -3',
      initialEquationOrState: '{ 4x + 3y = 18, x - 3y = -3 }',
      targetState: 'x = 3, y = 2 [VERIFIED]',
      optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SIMPLIFY',
          resultingState: '5x = 15 => x = 3',
          explanation: 'Eliminated 3y term: 5x = 15 yields x = 3.',
          damageValue: 40,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: '3 - 3y = -3 => y = 2',
          explanation: 'Substituted x = 3: -3y = -6 implies y = 2.',
          damageValue: 50,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '4(3) + 3(2) = 18 [TRUE]',
          explanation: 'Verification confirms 12 + 6 = 18.',
          damageValue: 30,
        },
      ],
      misconceptions: [],
    },
  ],

  // -------------------------------------------------------------
  // MATHEMATICS LEVEL 3: Radical Boundary (Discriminant & Radicals)
  // -------------------------------------------------------------
  'mathematics_3': [
    {
      id: 'math_l3_q1',
      conceptKey: 'math_roots_radicals',
      subject: 'mathematics',
      levelNumber: 3,
      difficulty: 3,
      objective: 'Isolate radical expressions and compute the exact roots.',
      problemStatement: 'Isolate radicals and determine exact roots of: x² - 4x + 1 = 0',
      initialEquationOrState: 'x² - 4x + 1 = 0',
      targetState: 'x = 2 ± √3 [VERIFIED]',
      optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SIMPLIFY',
          resultingState: '(x - 2)² - 3 = 0 => (x - 2)² = 3',
          explanation: 'Completed the square to isolate the radical component.',
          damageValue: 40,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: 'x - 2 = ±√3 => x = 2 ± √3',
          explanation: 'Extracted both radical roots using the quadratic discriminant.',
          damageValue: 50,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '(2+√3)² - 4(2+√3) + 1 = 0 [AXIOM SOUND]',
          explanation: 'Radical conjugate confirmed through backward substitution.',
          damageValue: 35,
        },
      ],
      misconceptions: [],
    },
    {
      id: 'math_l3_q2',
      conceptKey: 'math_roots_radicals',
      subject: 'mathematics',
      levelNumber: 3,
      difficulty: 3,
      objective: 'Isolate radical expressions and compute the exact roots.',
      problemStatement: 'Isolate radicals and determine exact roots of: x² - 6x + 2 = 0',
      initialEquationOrState: 'x² - 6x + 2 = 0',
      targetState: 'x = 3 ± √7 [VERIFIED]',
      optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SIMPLIFY',
          resultingState: '(x - 3)² - 7 = 0 => (x - 3)² = 7',
          explanation: 'Completed the square: (x - 3)² = 7.',
          damageValue: 40,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: 'x - 3 = ±√7 => x = 3 ± √7',
          explanation: 'Extracted roots x = 3 ± √7.',
          damageValue: 50,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '(3+√7)² - 6(3+√7) + 2 = 0 [TRUE]',
          explanation: 'Verified conjugate radical balance.',
          damageValue: 35,
        },
      ],
      misconceptions: [],
    },
    {
      id: 'math_l3_q3',
      conceptKey: 'math_roots_radicals',
      subject: 'mathematics',
      levelNumber: 3,
      difficulty: 3,
      objective: 'Isolate radical expressions and compute the exact roots.',
      problemStatement: 'Isolate radicals and determine exact roots of: x² - 2x - 1 = 0',
      initialEquationOrState: 'x² - 2x - 1 = 0',
      targetState: 'x = 1 ± √2 [VERIFIED]',
      optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SIMPLIFY',
          resultingState: '(x - 1)² - 2 = 0 => (x - 1)² = 2',
          explanation: 'Completed square: (x - 1)² = 2.',
          damageValue: 40,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: 'x = 1 ± √2',
          explanation: 'Square root extraction yields x = 1 ± √2.',
          damageValue: 50,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '1 + 2√2 + 2 - 2(1+√2) - 1 = 0 [TRUE]',
          explanation: 'Radical verified.',
          damageValue: 35,
        },
      ],
      misconceptions: [],
    },
  ],

  // -------------------------------------------------------------
  // MATHEMATICS LEVEL 4: Verification & Extraneous Roots
  // -------------------------------------------------------------
  'mathematics_4': [
    {
      id: 'math_l4_q1',
      conceptKey: 'math_verification',
      subject: 'mathematics',
      levelNumber: 4,
      difficulty: 4,
      objective: 'Evaluate candidate solutions and reject extraneous roots.',
      problemStatement: 'Solve the radical constraint: √(2x + 3) = x (Constraint: x ≥ 0)',
      initialEquationOrState: '√(2x + 3) = x (Constraint: x ≥ 0)',
      targetState: 'x = 3 [x = -1 EXTRANEOUS REJECTED]',
      optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SIMPLIFY',
          resultingState: '2x + 3 = x² => x² - 2x - 3 = 0',
          explanation: 'Squared both sides to eliminate the radical constraint.',
          damageValue: 45,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: '(x - 3)(x + 1) = 0 => x = 3, x = -1',
          explanation: 'Factored polynomial yielding algebraic candidate roots x = 3 and x = -1.',
          damageValue: 55,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '√(2(3)+3) = 3 [TRUE] | √(-2+3) ≠ -1 [EXTRANEOUS DROPPED]',
          explanation: 'Tested domain constraint x ≥ 0. Root x = -1 generates invalid negative radical.',
          damageValue: 40,
        },
      ],
      misconceptions: [],
    },
    {
      id: 'math_l4_q2',
      conceptKey: 'math_verification',
      subject: 'mathematics',
      levelNumber: 4,
      difficulty: 4,
      objective: 'Evaluate candidate solutions and reject extraneous roots.',
      problemStatement: 'Solve the radical constraint: √(x + 6) = x (Constraint: x ≥ 0)',
      initialEquationOrState: '√(x + 6) = x (Constraint: x ≥ 0)',
      targetState: 'x = 3 [x = -2 EXTRANEOUS REJECTED]',
      optimalSequence: ['SIMPLIFY', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SIMPLIFY',
          resultingState: 'x + 6 = x² => x² - x - 6 = 0',
          explanation: 'Squared both sides: x² - x - 6 = 0.',
          damageValue: 45,
        },
        {
          stepIndex: 1,
          operationKey: 'SOLVE',
          resultingState: '(x - 3)(x + 2) = 0 => x = 3, x = -2',
          explanation: 'Candidate roots: x = 3, x = -2.',
          damageValue: 55,
        },
        {
          stepIndex: 2,
          operationKey: 'VERIFY',
          resultingState: '√(3+6)=3 [VALID] | √(-2+6)≠-2 [EXTRANEOUS DROPPED]',
          explanation: 'Rejected x = -2 due to square root principal sign.',
          damageValue: 40,
        },
      ],
      misconceptions: [],
    },
  ],

  // -------------------------------------------------------------
  // MATHEMATICS LEVEL 5: Singularity Archon (Realm Boss Exam)
  // -------------------------------------------------------------
  'mathematics_5': [
    {
      id: 'math_l5_q1',
      conceptKey: 'math_singularity',
      subject: 'mathematics',
      levelNumber: 5,
      difficulty: 5,
      objective: 'Synthesize transformed quadratic decomposition and prove the constrained root.',
      problemStatement: 'Constrained Archon Singularity: P(t) = 2(t - 1)² + 7(t - 1) + 3 = 0, bounded by domain t > 0.',
      initialEquationOrState: '2(t - 1)² + 7(t - 1) + 3 = 0 [Domain: t > 0]',
      targetState: 't = 1/2 [SINGULARITY COLLAPSED]',
      correctAnswer: 't = 1/2',
      optimalSequence: ['SUBSTITUTE', 'SIMPLIFY', 'FACTOR', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SUBSTITUTE',
          resultingState: '2u² + 7u + 3 = 0 [u = t - 1, t > 0]',
          explanation: 'Substituted auxiliary variable u = t - 1 to transform into canonical non-monic quadratic.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'SIMPLIFY',
          resultingState: '2u² + 6u + u + 3 = 0',
          explanation: 'Partitioned middle term with ac = 6 into 6u + u for binomial grouping.',
          damageValue: 35,
        },
        {
          stepIndex: 2,
          operationKey: 'FACTOR',
          resultingState: '(2u + 1)(u + 3) = 0',
          explanation: 'Grouped terms to extract binomial factors: (2u + 1)(u + 3) = 0.',
          damageValue: 40,
        },
        {
          stepIndex: 3,
          operationKey: 'SOLVE',
          resultingState: 'u = -1/2 (t = 1/2), u = -3 (t = -2) [t = -2 REJECTED]',
          explanation: 'Extracted roots and strictly rejected extraneous candidate t = -2 due to domain condition t > 0. Surviving root: t = 1/2.',
          damageValue: 45,
        },
        {
          stepIndex: 4,
          operationKey: 'VERIFY',
          resultingState: 'SINGULARITY COLLAPSED [ABSOLUTE HARMONY]',
          explanation: 'Substituted surviving root into P(1/2) = 2(-1/2)² + 7(-1/2) + 3 = 0. Absolute mathematical harmony established!',
          damageValue: 50,
        },
      ],
      alternativePaths: [
        {
          id: 'path_alt_rearrange',
          name: 'Method B: Polynomial Rearrangement & Factorization',
          operations: ['REARRANGE', 'FACTOR', 'SOLVE', 'VERIFY'],
          educationalMethod: 'Algebraic Polynomial Expansion & Reduction',
          difficulty: 5,
          completionCondition: 't = 1/2 [SINGULARITY COLLAPSED]',
          transformations: [
            {
              stepIndex: 0,
              operationKey: 'REARRANGE',
              resultingState: '2t² + 3t - 2 = 0 [Domain: t > 0]',
              explanation: 'Expanded 2(t² - 2t + 1) + 7t - 7 + 3 and collected like terms to form standard quadratic.',
              damageValue: 40,
            },
            {
              stepIndex: 1,
              operationKey: 'FACTOR',
              resultingState: '(2t - 1)(t + 2) = 0',
              explanation: 'Factored polynomial into (2t - 1)(t + 2) = 0.',
              damageValue: 40,
            },
            {
              stepIndex: 2,
              operationKey: 'SOLVE',
              resultingState: 't = 1/2, t = -2 [REJECTED t = -2]',
              explanation: 'Extracted roots and rejected negative root per constraint t > 0.',
              damageValue: 50,
            },
            {
              stepIndex: 3,
              operationKey: 'VERIFY',
              resultingState: 'SINGULARITY COLLAPSED [ABSOLUTE HARMONY]',
              explanation: 'Verified surviving root t = 1/2 in original quadratic equation.',
              damageValue: 50,
            },
          ],
        },
      ],
      misconceptions: [],
    },
    {
      id: 'math_l5_q2',
      conceptKey: 'math_singularity',
      subject: 'mathematics',
      levelNumber: 5,
      difficulty: 5,
      objective: 'Synthesize variable substitution on constrained energy dissipation model.',
      problemStatement: 'Singularity Dissipation Model: E(x) = 3(x - 2)² + 5(x - 2) - 2 = 0, bounded by domain x > 2.',
      initialEquationOrState: '3(x - 2)² + 5(x - 2) - 2 = 0 [Domain: x > 2]',
      targetState: 'x = 7/3 [SINGULARITY COLLAPSED]',
      correctAnswer: 'x = 7/3',
      optimalSequence: ['SUBSTITUTE', 'SIMPLIFY', 'FACTOR', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SUBSTITUTE',
          resultingState: '3u² + 5u - 2 = 0 [u = x - 2, x > 2]',
          explanation: 'Set u = x - 2 to collapse transformed polynomial into standard form.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'SIMPLIFY',
          resultingState: '3u² + 6u - u - 2 = 0',
          explanation: 'Decomposed middle coefficient with product ac = -6 into 6u - u.',
          damageValue: 35,
        },
        {
          stepIndex: 2,
          operationKey: 'FACTOR',
          resultingState: '(3u - 1)(u + 2) = 0',
          explanation: 'Grouped terms into non-monic binomial factors: (3u - 1)(u + 2) = 0.',
          damageValue: 40,
        },
        {
          stepIndex: 3,
          operationKey: 'SOLVE',
          resultingState: 'u = 1/3 (x = 7/3), u = -2 (x = 0) [x = 0 REJECTED]',
          explanation: 'Solved roots. Eliminated x = 0 due to constraint x > 2. Surviving root: x = 7/3.',
          damageValue: 45,
        },
        {
          stepIndex: 4,
          operationKey: 'VERIFY',
          resultingState: 'SINGULARITY COLLAPSED [ABSOLUTE HARMONY]',
          explanation: 'Confirmed E(7/3) = 3(1/3)² + 5(1/3) - 2 = 1/3 + 5/3 - 2 = 0.',
          damageValue: 50,
        },
      ],
      alternativePaths: [
        {
          id: 'path_alt_rearrange_q2',
          name: 'Method B: Polynomial Rearrangement & Factorization',
          operations: ['REARRANGE', 'FACTOR', 'SOLVE', 'VERIFY'],
          educationalMethod: 'Algebraic Polynomial Expansion & Reduction',
          difficulty: 5,
          completionCondition: 'x = 7/3 [SINGULARITY COLLAPSED]',
          transformations: [
            {
              stepIndex: 0,
              operationKey: 'REARRANGE',
              resultingState: '3x² - 7x = 0 [Domain: x > 2]',
              explanation: 'Expanded 3(x² - 4x + 4) + 5x - 10 - 2 = 3x² - 7x = 0.',
              damageValue: 40,
            },
            {
              stepIndex: 1,
              operationKey: 'FACTOR',
              resultingState: 'x(3x - 7) = 0',
              explanation: 'Factored common term x: x(3x - 7) = 0.',
              damageValue: 40,
            },
            {
              stepIndex: 2,
              operationKey: 'SOLVE',
              resultingState: 'x = 7/3, x = 0 [REJECTED x = 0]',
              explanation: 'Extracted roots and rejected x = 0 per constraint x > 2.',
              damageValue: 50,
            },
            {
              stepIndex: 3,
              operationKey: 'VERIFY',
              resultingState: 'SINGULARITY COLLAPSED [ABSOLUTE HARMONY]',
              explanation: 'Verified surviving root x = 7/3 in original quadratic.',
              damageValue: 50,
            },
          ],
        },
      ],
      misconceptions: [],
    },
    {
      id: 'math_l5_q3',
      conceptKey: 'math_singularity',
      subject: 'mathematics',
      levelNumber: 5,
      difficulty: 5,
      objective: 'Deconstruct coupled non-linear system and eliminate invalid coordinates.',
      problemStatement: 'Coupled Coordinate Singularity: Q(y) = 2(y + 1)² - 5(y + 1) + 2 = 0, with boundary y > 0.',
      initialEquationOrState: '2(y + 1)² - 5(y + 1) + 2 = 0 [Domain: y > 0]',
      targetState: 'y = 1 [SINGULARITY COLLAPSED]',
      correctAnswer: 'y = 1',
      optimalSequence: ['SUBSTITUTE', 'SIMPLIFY', 'FACTOR', 'SOLVE', 'VERIFY'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'SUBSTITUTE',
          resultingState: '2u² - 5u + 2 = 0 [u = y + 1, y > 0]',
          explanation: 'Substituted u = y + 1 to convert to standard quadratic.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'SIMPLIFY',
          resultingState: '2u² - 4u - u + 2 = 0',
          explanation: 'Split middle term with ac = 4 into -4u - u.',
          damageValue: 35,
        },
        {
          stepIndex: 2,
          operationKey: 'FACTOR',
          resultingState: '(2u - 1)(u - 2) = 0',
          explanation: 'Extracted binomial product: (2u - 1)(u - 2) = 0.',
          damageValue: 40,
        },
        {
          stepIndex: 3,
          operationKey: 'SOLVE',
          resultingState: 'u = 1/2 (y = -1/2), u = 2 (y = 1) [y = -1/2 REJECTED]',
          explanation: 'Extracted candidate values. Eliminated y = -1/2 (since y > 0). Surviving root: y = 1.',
          damageValue: 45,
        },
        {
          stepIndex: 4,
          operationKey: 'VERIFY',
          resultingState: 'SINGULARITY COLLAPSED [ABSOLUTE HARMONY]',
          explanation: 'Verified Q(1) = 2(2)² - 5(2) + 2 = 8 - 10 + 2 = 0.',
          damageValue: 50,
        },
      ],
      alternativePaths: [
        {
          id: 'path_alt_rearrange_q3',
          name: 'Method B: Polynomial Rearrangement & Factorization',
          operations: ['REARRANGE', 'FACTOR', 'SOLVE', 'VERIFY'],
          educationalMethod: 'Algebraic Polynomial Expansion & Reduction',
          difficulty: 5,
          completionCondition: 'y = 1 [SINGULARITY COLLAPSED]',
          transformations: [
            {
              stepIndex: 0,
              operationKey: 'REARRANGE',
              resultingState: '2y² - y - 1 = 0 [Domain: y > 0]',
              explanation: 'Expanded 2(y² + 2y + 1) - 5y - 5 + 2 = 2y² - y - 1 = 0.',
              damageValue: 40,
            },
            {
              stepIndex: 1,
              operationKey: 'FACTOR',
              resultingState: '(2y + 1)(y - 1) = 0',
              explanation: 'Factored polynomial into (2y + 1)(y - 1) = 0.',
              damageValue: 40,
            },
            {
              stepIndex: 2,
              operationKey: 'SOLVE',
              resultingState: 'y = 1, y = -1/2 [REJECTED y = -1/2]',
              explanation: 'Extracted roots and rejected y = -1/2 per domain y > 0.',
              damageValue: 50,
            },
            {
              stepIndex: 3,
              operationKey: 'VERIFY',
              resultingState: 'SINGULARITY COLLAPSED [ABSOLUTE HARMONY]',
              explanation: 'Verified surviving root y = 1 in original equation.',
              damageValue: 50,
            },
          ],
        },
      ],
      misconceptions: [],
    },
  ],

  // -------------------------------------------------------------
  // COMPUTER SCIENCE LEVEL 5: The Turing Archon (Realm Boss Exam)
  // -------------------------------------------------------------
  'computerScience_5': [
    {
      id: 'cs_l5_q1',
      conceptKey: 'cs_singularity',
      subject: 'computerScience',
      levelNumber: 5,
      difficulty: 5,
      objective: 'Synthesize invariant bounds and memoized transitions to halt the recursion in O(log n).',
      problemStatement: 'Partitioned circular search buffer B[0..n-1] evaluates window bounds while maintaining the invariant that the inflection pivot lies in the active interval.',
      initialEquationOrState: 'Buffer: B[0..n-1] (Rotated) | Invariant: Inflection ∈ [low, high]',
      targetState: 'Pivot Located in O(log n) [TURING VICTORY]',
      correctAnswer: 'O(log n)',
      optimalSequence: ['INITIALIZE', 'PARTITION', 'COMPARE', 'MEMOIZE', 'TERMINATE'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'INITIALIZE',
          resultingState: 'Tape bounded: Invariant pinned to [low=0, high=n-1]',
          explanation: 'Established loop invariants and bounded pointer search space.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'PARTITION',
          resultingState: 'Midpoint pivot isolated: mid = ⌊(low + high) / 2⌋',
          explanation: 'Segmented search space into equal halves around the pivot.',
          damageValue: 35,
        },
        {
          stepIndex: 2,
          operationKey: 'COMPARE',
          resultingState: 'State transition validated: Monotonic subarray identified',
          explanation: 'Evaluated ordering predicate to prove inflection window containment.',
          damageValue: 40,
        },
        {
          stepIndex: 3,
          operationKey: 'MEMOIZE',
          resultingState: 'Interval memoized: Eliminating redundant branch exploration',
          explanation: 'Cached pruned state boundaries into optimal polynomial DAG.',
          damageValue: 45,
        },
        {
          stepIndex: 4,
          operationKey: 'TERMINATE',
          resultingState: 'TAPE HALTED: Search space reduced in O(log n) [TOTAL CS MASTERY]',
          explanation: 'Algorithm terminated with proven invariant and logarithmic complexity.',
          damageValue: 50,
        },
      ],
      alternativePaths: [
        {
          id: 'path_alt_direct_halving',
          name: 'Method B: Direct Boundary Halving & Memoization',
          operations: ['INITIALIZE', 'COMPARE', 'MEMOIZE', 'TERMINATE'],
          educationalMethod: 'Direct Logarithmic Interval Halving',
          difficulty: 5,
          completionCondition: 'Pivot Located in O(log n) [TURING VICTORY]',
          transformations: [
            {
              stepIndex: 0,
              operationKey: 'INITIALIZE',
              resultingState: 'Tape bounded: Invariant pinned to [low=0, high=n-1]',
              explanation: 'Bounded active search window.',
              damageValue: 40,
            },
            {
              stepIndex: 1,
              operationKey: 'COMPARE',
              resultingState: 'State transition validated: Boundary halved directly',
              explanation: 'Evaluated bounds directly against target predicate.',
              damageValue: 45,
            },
            {
              stepIndex: 2,
              operationKey: 'MEMOIZE',
              resultingState: 'State graph collapsed into optimal DAG',
              explanation: 'Cached state transitions to avoid exponential recursion.',
              damageValue: 45,
            },
            {
              stepIndex: 3,
              operationKey: 'TERMINATE',
              resultingState: 'TAPE HALTED: Search space reduced in O(log n) [TOTAL CS MASTERY]',
              explanation: 'Halting invariant verified deterministically.',
              damageValue: 50,
            },
          ],
        },
      ],
      misconceptions: [],
    },
    {
      id: 'cs_l5_q2',
      conceptKey: 'cs_singularity',
      subject: 'computerScience',
      levelNumber: 5,
      difficulty: 5,
      objective: 'Synthesize divide-and-conquer recurrence invariant and prove logarithmic polynomial bound.',
      problemStatement: 'Recurrence Singularity: T(n) = 2T(n/2) + O(n). Analyze recurrence tree, memoize subproblems, and verify optimal bound.',
      initialEquationOrState: 'T(n) = 2T(n/2) + O(n) | Recurrence Tree Unfolded',
      targetState: 'Complexity Proven: T(n) = O(n log n) [TURING VICTORY]',
      correctAnswer: 'O(n log n)',
      optimalSequence: ['INITIALIZE', 'PARTITION', 'COMPARE', 'MEMOIZE', 'TERMINATE'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'INITIALIZE',
          resultingState: 'Base case pinned: T(1) = O(1) | Recurrence depth = log₂n',
          explanation: 'Initialized recurrence tree boundaries and base case invariants.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'PARTITION',
          resultingState: 'Level work partitioned: Each level k performs n work',
          explanation: 'Analyzed work per level across 2^k subproblems of size n/2^k.',
          damageValue: 35,
        },
        {
          stepIndex: 2,
          operationKey: 'COMPARE',
          resultingState: 'Master Theorem case verified: f(n) = Θ(n^(log_b a))',
          explanation: 'Evaluated critical ratio comparing split work and combine work.',
          damageValue: 40,
        },
        {
          stepIndex: 3,
          operationKey: 'MEMOIZE',
          resultingState: 'Tree height collapsed: log₂n levels × n work cached',
          explanation: 'Memoized level summation to prevent exponential blowup.',
          damageValue: 45,
        },
        {
          stepIndex: 4,
          operationKey: 'TERMINATE',
          resultingState: 'Complexity Proven: T(n) = O(n log n) [TURING VICTORY]',
          explanation: 'Proved strict asymptotic bound and halted recurrence verification.',
          damageValue: 50,
        },
      ],
      alternativePaths: [
        {
          id: 'path_alt_direct_master',
          name: 'Method B: Direct Master Theorem Characterization',
          operations: ['INITIALIZE', 'COMPARE', 'MEMOIZE', 'TERMINATE'],
          educationalMethod: 'Direct Master Theorem Characterization',
          difficulty: 5,
          completionCondition: 'Complexity Proven: T(n) = O(n log n) [TURING VICTORY]',
          transformations: [
            {
              stepIndex: 0,
              operationKey: 'INITIALIZE',
              resultingState: 'Base case pinned: T(1) = O(1)',
              explanation: 'Bounded recurrence base state.',
              damageValue: 40,
            },
            {
              stepIndex: 1,
              operationKey: 'COMPARE',
              resultingState: 'Master Theorem parameters: a=2, b=2, k=1 matched Case 2',
              explanation: 'Compared asymptotic exponents directly.',
              damageValue: 45,
            },
            {
              stepIndex: 2,
              operationKey: 'MEMOIZE',
              resultingState: 'Summation collapsed into closed form',
              explanation: 'Cached closed form polynomial expression.',
              damageValue: 45,
            },
            {
              stepIndex: 3,
              operationKey: 'TERMINATE',
              resultingState: 'Complexity Proven: T(n) = O(n log n) [TURING VICTORY]',
              explanation: 'Terminated with exact theorem proof.',
              damageValue: 50,
            },
          ],
        },
      ],
      misconceptions: [],
    },
  ],

  // -------------------------------------------------------------
  // COMPUTER SCIENCE LEVEL 1: Array Invariants
  // -------------------------------------------------------------
  'computerScience_1': [
    {
      id: 'cs_l1_q1',
      conceptKey: 'cs_arrays_invariants',
      subject: 'computerScience',
      levelNumber: 1,
      difficulty: 1,
      objective: 'Establish sorting invariants and restore ascending order to the buffer.',
      problemStatement: 'Restore order to the unsorted memory buffer: [5, 2, 8, 1]',
      initialEquationOrState: 'Array: [5, 2, 8, 1] | Inversions Detected: 3',
      targetState: 'Array: [1, 2, 5, 8] [SORTED & VERIFIED]',
      optimalSequence: ['INITIALIZE', 'COMPARE', 'SWAP', 'TERMINATE'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'INITIALIZE',
          resultingState: 'Pointers set: i=0, j=1 | array[0]=5, array[1]=2',
          explanation: 'Loop bounds established. Scanning first adjacent pair.',
          damageValue: 25,
        },
        {
          stepIndex: 1,
          operationKey: 'COMPARE',
          resultingState: 'Evaluated: 5 > 2 => TRUE (Inversion detected)',
          explanation: 'Identified out-of-order sequence needing swap.',
          damageValue: 30,
        },
        {
          stepIndex: 2,
          operationKey: 'SWAP',
          resultingState: 'Swapped: [2, 5, 8, 1] | Inversions remaining: 2',
          explanation: 'Adjacent elements swapped to satisfy monotonic ordering.',
          damageValue: 35,
        },
        {
          stepIndex: 3,
          operationKey: 'TERMINATE',
          resultingState: 'Array: [1, 2, 5, 8] [SORTED & VERIFIED]',
          explanation: 'Pass completed with zero remaining inversions.',
          damageValue: 30,
        },
      ],
      misconceptions: [
        {
          triggerOperation: 'SWAP',
          atStepIndex: 0,
          diagnosisType: 'prerequisite_gap',
          title: 'Premature Swap without Comparison',
          diagnosisExplanation: 'Attempted to swap elements without comparing their values first.',
          enemyAdaptationName: 'Index Out of Bounds Shield',
          enemyAdaptationEffect: 'Deploys a 25-point defensive ward.',
          repairConcept: 'Two-Pointer Invariants',
          echoVaultId: 'vault_cs_invariants',
        },
      ],
    },
    {
      id: 'cs_l1_q2',
      conceptKey: 'cs_arrays_invariants',
      subject: 'computerScience',
      levelNumber: 1,
      difficulty: 1,
      objective: 'Establish sorting invariants and restore ascending order to the buffer.',
      problemStatement: 'Restore order to the unsorted memory buffer: [9, 4, 6, 2]',
      initialEquationOrState: 'Array: [9, 4, 6, 2] | Inversions Detected: 4',
      targetState: 'Array: [2, 4, 6, 9] [SORTED & VERIFIED]',
      optimalSequence: ['INITIALIZE', 'COMPARE', 'SWAP', 'TERMINATE'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'INITIALIZE',
          resultingState: 'Pointers set: i=0, j=1 | array[0]=9, array[1]=4',
          explanation: 'Loop bounds established. Scanning first adjacent pair.',
          damageValue: 25,
        },
        {
          stepIndex: 1,
          operationKey: 'COMPARE',
          resultingState: 'Evaluated: 9 > 4 => TRUE (Inversion detected)',
          explanation: 'Identified out-of-order sequence needing swap.',
          damageValue: 30,
        },
        {
          stepIndex: 2,
          operationKey: 'SWAP',
          resultingState: 'Swapped: [4, 9, 6, 2] | Inversions remaining: 3',
          explanation: 'Adjacent elements swapped to satisfy monotonic ordering.',
          damageValue: 35,
        },
        {
          stepIndex: 3,
          operationKey: 'TERMINATE',
          resultingState: 'Array: [2, 4, 6, 9] [SORTED & VERIFIED]',
          explanation: 'Pass completed with zero remaining inversions.',
          damageValue: 30,
        },
      ],
      misconceptions: [
        {
          triggerOperation: 'SWAP',
          atStepIndex: 0,
          diagnosisType: 'prerequisite_gap',
          title: 'Premature Swap without Comparison',
          diagnosisExplanation: 'Attempted to swap elements without comparing their values first.',
          enemyAdaptationName: 'Index Out of Bounds Shield',
          enemyAdaptationEffect: 'Deploys a 25-point defensive ward.',
          repairConcept: 'Two-Pointer Invariants',
          echoVaultId: 'vault_cs_invariants',
        },
      ],
    },
    {
      id: 'cs_l1_q3',
      conceptKey: 'cs_arrays_invariants',
      subject: 'computerScience',
      levelNumber: 1,
      difficulty: 1,
      objective: 'Establish sorting invariants and restore ascending order to the buffer.',
      problemStatement: 'Restore order to the unsorted memory buffer: [7, 3, 8, 1]',
      initialEquationOrState: 'Array: [7, 3, 8, 1] | Inversions Detected: 3',
      targetState: 'Array: [1, 3, 7, 8] [SORTED & VERIFIED]',
      optimalSequence: ['INITIALIZE', 'COMPARE', 'SWAP', 'TERMINATE'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'INITIALIZE',
          resultingState: 'Pointers set: i=0, j=1 | array[0]=7, array[1]=3',
          explanation: 'Loop bounds established.',
          damageValue: 25,
        },
        {
          stepIndex: 1,
          operationKey: 'COMPARE',
          resultingState: 'Evaluated: 7 > 3 => TRUE (Inversion detected)',
          explanation: 'Inversion confirmed.',
          damageValue: 30,
        },
        {
          stepIndex: 2,
          operationKey: 'SWAP',
          resultingState: 'Swapped: [3, 7, 8, 1] | Inversions remaining: 2',
          explanation: 'Swapped adjacent pair.',
          damageValue: 35,
        },
        {
          stepIndex: 3,
          operationKey: 'TERMINATE',
          resultingState: 'Array: [1, 3, 7, 8] [SORTED & VERIFIED]',
          explanation: 'Restored sorted invariant.',
          damageValue: 30,
        },
      ],
      misconceptions: [
        {
          triggerOperation: 'SWAP',
          atStepIndex: 0,
          diagnosisType: 'prerequisite_gap',
          title: 'Premature Swap without Comparison',
          diagnosisExplanation: 'Attempted to swap elements without comparing their values first.',
          enemyAdaptationName: 'Index Out of Bounds Shield',
          enemyAdaptationEffect: 'Deploys a 25-point defensive ward.',
          repairConcept: 'Two-Pointer Invariants',
          echoVaultId: 'vault_cs_invariants',
        },
      ],
    },
    {
      id: 'cs_l1_q4',
      conceptKey: 'cs_arrays_invariants',
      subject: 'computerScience',
      levelNumber: 1,
      difficulty: 1,
      objective: 'Establish sorting invariants and restore ascending order to the buffer.',
      problemStatement: 'Restore order to the unsorted memory buffer: [6, 1, 5, 2]',
      initialEquationOrState: 'Array: [6, 1, 5, 2] | Inversions Detected: 3',
      targetState: 'Array: [1, 2, 5, 6] [SORTED & VERIFIED]',
      optimalSequence: ['INITIALIZE', 'COMPARE', 'SWAP', 'TERMINATE'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'INITIALIZE',
          resultingState: 'Pointers set: i=0, j=1 | array[0]=6, array[1]=1',
          explanation: 'Pointers ready.',
          damageValue: 25,
        },
        {
          stepIndex: 1,
          operationKey: 'COMPARE',
          resultingState: 'Evaluated: 6 > 1 => TRUE',
          explanation: 'Comparison verified out of order.',
          damageValue: 30,
        },
        {
          stepIndex: 2,
          operationKey: 'SWAP',
          resultingState: 'Swapped: [1, 6, 5, 2]',
          explanation: 'Swapped out-of-order pair.',
          damageValue: 35,
        },
        {
          stepIndex: 3,
          operationKey: 'TERMINATE',
          resultingState: 'Array: [1, 2, 5, 6] [SORTED & VERIFIED]',
          explanation: 'Pass completed with invariant met.',
          damageValue: 30,
        },
      ],
      misconceptions: [
        {
          triggerOperation: 'SWAP',
          atStepIndex: 0,
          diagnosisType: 'prerequisite_gap',
          title: 'Premature Swap without Comparison',
          diagnosisExplanation: 'Attempted to swap elements without comparing their values first.',
          enemyAdaptationName: 'Index Out of Bounds Shield',
          enemyAdaptationEffect: 'Deploys a 25-point defensive ward.',
          repairConcept: 'Two-Pointer Invariants',
          echoVaultId: 'vault_cs_invariants',
        },
      ],
    },
  ],

  // -------------------------------------------------------------
  // COMPUTER SCIENCE LEVEL 2: Binary Search
  // -------------------------------------------------------------
  'computerScience_2': [
    {
      id: 'cs_l2_q1',
      conceptKey: 'cs_binary_search',
      subject: 'computerScience',
      levelNumber: 2,
      difficulty: 2,
      objective: 'Search the sorted buffer and locate the key index in O(log n) time.',
      problemStatement: 'Locate target key 11 within sorted memory buffer: [2, 4, 7, 11, 15]',
      initialEquationOrState: 'Buffer: [2, 4, 7, 11, 15] | Search Space: O(n)',
      targetState: 'Key 11 found at index 3 [O(log n) PROVEN]',
      optimalSequence: ['INITIALIZE', 'COMPARE', 'TERMINATE'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'INITIALIZE',
          resultingState: 'Pointers set: low=0, high=4, mid=2 (arr[mid]=7)',
          explanation: 'Established search boundaries over monotonic array.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'COMPARE',
          resultingState: 'Evaluated: target 11 > 7 => low = mid + 1 = 3',
          explanation: 'Halved search space using monotonic comparison predicate.',
          damageValue: 45,
        },
        {
          stepIndex: 2,
          operationKey: 'TERMINATE',
          resultingState: 'Target 11 identified at index 3! [O(log n) EFFICIENCY]',
          explanation: 'Logarithmic search terminated with exact key match.',
          damageValue: 40,
        },
      ],
      misconceptions: [],
    },
    {
      id: 'cs_l2_q2',
      conceptKey: 'cs_binary_search',
      subject: 'computerScience',
      levelNumber: 2,
      difficulty: 2,
      objective: 'Search the sorted buffer and locate the key index in O(log n) time.',
      problemStatement: 'Locate target key 17 within sorted memory buffer: [3, 8, 12, 17, 24]',
      initialEquationOrState: 'Buffer: [3, 8, 12, 17, 24] | Search Space: O(n)',
      targetState: 'Key 17 found at index 3 [O(log n) PROVEN]',
      optimalSequence: ['INITIALIZE', 'COMPARE', 'TERMINATE'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'INITIALIZE',
          resultingState: 'Pointers set: low=0, high=4, mid=2 (arr[mid]=12)',
          explanation: 'Initialized binary pointers.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'COMPARE',
          resultingState: 'Evaluated: target 17 > 12 => low = mid + 1 = 3',
          explanation: 'Discarded lower half.',
          damageValue: 45,
        },
        {
          stepIndex: 2,
          operationKey: 'TERMINATE',
          resultingState: 'Target 17 identified at index 3! [O(log n) EFFICIENCY]',
          explanation: 'Match confirmed.',
          damageValue: 40,
        },
      ],
      misconceptions: [],
    },
    {
      id: 'cs_l2_q3',
      conceptKey: 'cs_binary_search',
      subject: 'computerScience',
      levelNumber: 2,
      difficulty: 2,
      objective: 'Search the sorted buffer and locate the key index in O(log n) time.',
      problemStatement: 'Locate target key 14 within sorted memory buffer: [1, 5, 9, 14, 20]',
      initialEquationOrState: 'Buffer: [1, 5, 9, 14, 20] | Search Space: O(n)',
      targetState: 'Key 14 found at index 3 [O(log n) PROVEN]',
      optimalSequence: ['INITIALIZE', 'COMPARE', 'TERMINATE'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'INITIALIZE',
          resultingState: 'Pointers set: low=0, high=4, mid=2 (arr[mid]=9)',
          explanation: 'Initialized binary search pointers.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'COMPARE',
          resultingState: 'Evaluated: target 14 > 9 => low = mid + 1 = 3',
          explanation: 'Discarded lower half.',
          damageValue: 45,
        },
        {
          stepIndex: 2,
          operationKey: 'TERMINATE',
          resultingState: 'Target 14 identified at index 3! [O(log n) EFFICIENCY]',
          explanation: 'Match confirmed.',
          damageValue: 40,
        },
      ],
      misconceptions: [],
    },
    {
      id: 'cs_l2_q4',
      conceptKey: 'cs_binary_search',
      subject: 'computerScience',
      levelNumber: 2,
      difficulty: 2,
      objective: 'Search the sorted buffer and locate the key index in O(log n) time.',
      problemStatement: 'Locate target key 22 within sorted memory buffer: [4, 10, 16, 22, 30]',
      initialEquationOrState: 'Buffer: [4, 10, 16, 22, 30] | Search Space: O(n)',
      targetState: 'Key 22 found at index 3 [O(log n) PROVEN]',
      optimalSequence: ['INITIALIZE', 'COMPARE', 'TERMINATE'],
      stepTransformations: [
        {
          stepIndex: 0,
          operationKey: 'INITIALIZE',
          resultingState: 'Pointers set: low=0, high=4, mid=2 (arr[mid]=16)',
          explanation: 'Search boundaries set.',
          damageValue: 35,
        },
        {
          stepIndex: 1,
          operationKey: 'COMPARE',
          resultingState: 'Evaluated: target 22 > 16 => low = mid + 1 = 3',
          explanation: 'Halved search range.',
          damageValue: 45,
        },
        {
          stepIndex: 2,
          operationKey: 'TERMINATE',
          resultingState: 'Target 22 identified at index 3! [O(log n) EFFICIENCY]',
          explanation: 'Terminated with exact key.',
          damageValue: 40,
        },
      ],
      misconceptions: [],
    },
  ],
};
